CarGraphNode.prototype=new Node;CarGraphNode.prototype.constructor=CarGraphNode;CarGraphNode.prototype.parentNode=Node.prototype;CarGraphNode.authoringToolName="Car Graph";CarGraphNode.authoringToolDescription="Lets students draw graphs and have cars move according to the graph";function CarGraphNode(a,b){this.view=b;this.type=a;this.prevWorkNodeIds=[]}CarGraphNode.prototype.parseDataJSONObj=function(a){return CARGRAPHSTATE.prototype.parseDataJSONObj(a)};
CarGraphNode.prototype.translateStudentWork=function(a){return a};
CarGraphNode.prototype.smartFilter=function(a){for(var b={filtered:!1,maxError:0,avgError:0,errMargin:0,error:!1},c=this.content.getContentJSON(),e=0;e<c.dynamicImages.length;e++){var d=c.dynamicImages[e].id;if(a.getPredictionObjByPredictionId(d)===null){b.error=!0;break}var g=a.getPredictionObjByPredictionId(d).predictions,f=this.getResultObjByResultId(d);if(f===null){b.error=!0;break}d=0.5;if(f.maxErrorMargin!==null&&f.maxErrorMargin!==void 0)d=f.maxErrorMargin;for(var f=f.expectedPoints,j=new CARGRAPH(this),
h=0,i=!1,l=parseInt(c.graphParams.xmin)+1;l<parseInt(c.graphParams.xmax);l++){var k=j.getYValueObj(l,f),m=j.getYValueObj(l,g),k=Math.abs(k-m)*1;if(k>b.maxError)b.maxError=k;h+=k;k>d&&(i=!0)}b.avgError=h/l;b.filtered=i;b.errMargin=d}return b};CarGraphNode.prototype.getResultObjByResultId=function(a){for(var b=0;b<this.content.getContentJSON().expectedResults.length;b++)if(this.content.getContentJSON().expectedResults[b].id==a)return this.content.getContentJSON().expectedResults[b];return null};
CarGraphNode.prototype.onExit=function(){var a=this.smartFilter(this.view.state.getLatestWorkByNodeId(this.id));if(this.view.studentStatus==null)this.view.studentStatus=new StudentStatus;if(a.maxError>10){if(this.view.studentStatus.alertables==null)this.view.studentStatus.alertables=[];var b=this.id,c=a.maxError,e=this.view.project.getStepNumberAndTitle(this.id),d=this.type,a="Autoscore returned "+a.maxError+". This might mean that the student needs help.",g=(new Date).getMilliseconds();this.view.studentStatus.addAlertable(new StudentAlertable(5,
b,"autoScoreResult",c,e,d,a,g))}else this.view.studentStatus.removeAlertable(this.id);if(this.contentPanel){this.contentPanel.save&&this.contentPanel.save();try{if(this.contentPanel.onExit)try{this.contentPanel.onExit()}catch(f){}}catch(j){history.back()}}};
CarGraphNode.prototype.renderGradingView=function(a,b,c){var e=new CARGRAPH(this,this.view);c==null&&(c="");var d=b.id,b=b.getLatestWork();e.carGraphState=b;e.parseGraphParams(this.content.getContentJSON().graphParams);var g=createElement(document,"div",{id:c+"carGraphGraphDiv_"+d,style:"width:400px;height:200px;"}),f=createElement(document,"div",{id:c+"carGraphGraphCheckBoxesDiv_"+d}),j=createElement(document,"div",{id:c+"carGraphAnnotationsDiv_"+d}),c=createElement(document,"div",{id:c+"carGraphResponseDiv_"+
d});$("#"+a).append(g);$("#"+a).append(f);$("#"+a).append(j);$("#"+a).append(c);var h=this.smartFilter(b);if(h.error!==!0){var i=createElement(document,"div",{id:"smartFilter_"+d,"class":"smartFilter"});i.innerHTML+="<span class='maxError' style='color:red'>"+h.maxError+"</span>";i.innerHTML+="<span class='avgError' style='color:green; display:none'>"+h.avgError+"</span>";i.innerHTML+="<span class='errMargin' style='color:yellow; display:none'>"+h.errMargin+"</span>"}$("#"+a).append(i);e.plotData(g.id,
f.id);$("#"+g.id).bind("mouseover",function(){$(".activeAnnotationToolTip").hide()});$("#"+g.id).bind("mouseleave",function(){$(".activeAnnotationToolTip").show()});a=b.getAnnotationsHtml();$("#"+j.id).html(a);a=b.response;a=this.view.replaceSlashNWithBR(a);$("#"+c.id).html(a)};
CarGraphNode.prototype.showSmartFilter=function(a){var b=function(a){$(".maxError").each(function(){parseFloat($(this).html())<a?($(this).parents(".studentWorkRow").hide(),$(this).parents(".studentWorkRow").removeClass("smartFilterShow"),$(this).parents(".studentWorkRow").addClass("smartFilterHide")):($(this).parents(".studentWorkRow").show(),$(this).parents(".studentWorkRow").removeClass("smartFilterHide"),$(this).parents(".studentWorkRow").addClass("smartFilterShow"))})};a?($("#onlyShowSmartFilteredItemsSlider").length==
0&&(b(11),$("#onlyShowSmartFilteredItemsText").append("<div style='width:80%' id='smartFilter'><div style='color:green'><span><- SLIDE LEFT: More errors</span><span style='margin-left:150px'>Showing <span id='currentDisplayedWorkCount'></span> work with highest margin of error more than <span id='currentSliderValue'>11</span></span><span style='float:right'>SLIDE RIGHT: Less errors -></span></div><div id='onlyShowSmartFilteredItemsSlider'></div></div>"),$("#onlyShowSmartFilteredItemsSlider").slider({value:11,
min:0,max:22,slide:function(a,e){var d=22-e.value;b(d);$("#currentSliderValue").html(d);typeof eventManager!="undefined"&&eventManager.fire("filterStudentRows")}})),$(".studentWorkRow.noWork").hide(),$("#smartFilter").show()):($(".studentWorkRow.noWork").filter(":visible").show(),$("#smartFilter").hide());return!0};CarGraphNode.prototype.getHTMLContentTemplate=function(){return createContent("node/cargraph/cargraph.html")};NodeFactory.addNode("CarGraphNode",CarGraphNode);
typeof eventManager!="undefined"&&eventManager.fire("scriptLoaded","vle/node/cargraph/CarGraphNode.js");View.prototype.cargraphDispatcher=function(a,b,c){a=="cargraphUpdatePrompt"&&c.CarGraphNode.updatePrompt()};for(var events=["cargraphUpdatePrompt"],x=0;x<events.length;x++)componentloader.addEvent(events[x],"cargraphDispatcher");typeof eventManager!="undefined"&&eventManager.fire("scriptLoaded","vle/node/cargraph/cargraphEvents.js");
if(typeof eventManager != 'undefined'){eventManager.fire('scriptLoaded', 'vle/node/cargraph/cargraph_core_min.js');}
