function VLE_STATE(){this.visitedNodes=[];this.dataId=this.userName=null}VLE_STATE.prototype.setUserName=function(b){this.userName=b};VLE_STATE.prototype.setDataId=function(b){this.dataId=b};VLE_STATE.prototype.getCurrentNodeVisit=function(){return this.visitedNodes.length==0?null:this.visitedNodes[this.visitedNodes.length-1]};VLE_STATE.prototype.endCurrentNodeVisit=function(){var b=this.getCurrentNodeVisit();if(b)b.visitEndTime=Date.parse(new Date)};VLE_STATE.prototype.saveState=function(){};
VLE_STATE.prototype.getNodeVisitsByNodeId=function(b){for(var c=[],a=0;a<this.visitedNodes.length;a++)this.visitedNodes[a].nodeId==b&&c.push(this.visitedNodes[a]);return c};VLE_STATE.prototype.getNodeVisitsWithWorkByNodeId=function(b){for(var c=[],a=0;a<this.visitedNodes.length;a++)this.visitedNodes[a].nodeId==b&&this.visitedNodes[a].getLatestWork()!=""&&c.push(this.visitedNodes[a]);return c};
VLE_STATE.prototype.getLatestNodeVisitByNodeId=function(b,c){for(var a=this.visitedNodes.length-1;a>=0;a--)if(this.visitedNodes[a].nodeId==b)if(c)return this.visitedNodes[a];else if(this.visitedNodes[a].nodeType=="HtmlNode"||this.visitedNodes[a].nodeType=="OutsideUrlNode")return this.visitedNodes[a];else if(this.visitedNodes[a].getLatestWork()!="")return this.visitedNodes[a];return null};
VLE_STATE.prototype.getLatestWorkByNodeId=function(b){for(var c=this.visitedNodes.length-1;c>=0;c--){var a=this.visitedNodes[c];if(a.nodeId==b&&(a=a.getLatestWork(),a!=""))return a}return""};VLE_STATE.prototype.parseDataJSONString=function(b,c){for(var a=$.parseJSON(b),d=[],e=0;e<a.vle_states.length;e++)d.push(VLE_STATE.prototype.parseDataJSONObj(a.vle_states[e]));return d.length==1&&!c?d[0]:d};
VLE_STATE.prototype.parseDataJSONObj=function(b){var c=new VLE_STATE;c.userName=b.userName;c.dataId=b.userId;if(b.visitedNodes!=null)for(var a=0;a<b.visitedNodes.length;a++){var d=NODE_VISIT.prototype.parseDataJSONObj(b.visitedNodes[a]);d!=null&&c.visitedNodes.push(d)}return c};
VLE_STATE.prototype.setCurrentNodeVisit=function(b){this.getCurrentNodeVisit();if(b.type=="DuplicateNode"){var c=b.getNode(),c=new NODE_VISIT(c.id,c.type);c.duplicateId=b.id}else c=new NODE_VISIT(b.id,b.type),c.duplicateId=void 0;this.visitedNodes.push(c)};
VLE_STATE.prototype.getNodeVisitsByNodeType=function(b){for(var c={},a=0;a<this.visitedNodes.length;a++)this.visitedNodes[a].nodeType==b&&(c[this.visitedNodes[a].nodeId]||(c[this.visitedNodes[a].nodeId]=[]),c[this.visitedNodes[a].nodeId].push(this.visitedNodes[a]));return c};VLE_STATE.prototype.getLatestVisit=function(){var b=null;this.visitedNodes.length>0&&(b=this.visitedNodes[this.visitedNodes.length-1]);return b};
VLE_STATE.prototype.getLatestCompletedVisit=function(){for(var b=null,c=this.visitedNodes.length-1;c>=0;c--){var a=this.visitedNodes[c];if(a.visitStartTime!=null&&a.visitEndTime!=null){b=a;break}}return b};VLE_STATE.prototype.getLastTimeVisited=function(){var b=0;if(this.visitedNodes.length>1)b=this.visitedNodes[this.visitedNodes.length-2].visitStartTime;return b};VLE_STATE.prototype.getNodeVisitById=function(b){for(var c=0;c<this.visitedNodes.length;c++){var a=this.visitedNodes[c];if(a.id==b)return a}return null};
typeof eventManager!="undefined"&&eventManager.fire("scriptLoaded","vle/data/vlestate.js");function NODE_VISIT(b,c,a,d,e){this.nodeId=b;this.nodeType=c;this.visitPostTime=null;this.hintStates=[];arguments.length==2?(this.nodeStates=[],this.visitStartTime=Date.parse(new Date),this.visitEndTime=null):(this.nodeStates=a,this.visitStartTime=d,this.visitEndTime=e)}NODE_VISIT.prototype.getNodeId=function(){return this.nodeId};
NODE_VISIT.prototype.parseDataJSONObj=function(b,c){var a=new NODE_VISIT;a.id=b.stepWorkId;a.nodeId=b.nodeId;a.nodeType=b.nodeType;a.visitStartTime=b.visitStartTime;a.visitEndTime=b.visitEndTime;a.visitPostTime=b.visitPostTime;a.duplicateId=b.duplicateId;var d=null,d=typeof env=="undefined"?c.getProject().getNodeById(a.nodeId):env.getProject().getNodeById(a.nodeId);if(!d||d==null)return null;var e=[];if(b.nodeStates!=null)for(var g=0;g<b.nodeStates.length;g++){var f=b.nodeStates[g];f!=null&&(f=d.parseDataJSONObj(f),
e.push(f))}a.nodeStates=e;return a};NODE_VISIT.prototype.getLatestState=function(){return this.nodeStates[this.nodeStates.length-1]};NODE_VISIT.prototype.getLatestWork=function(){for(var b=this.nodeStates.length-1;b>=0;b--)if(this.nodeStates[b]!=null&&this.nodeStates[b].getStudentWork()!=null&&this.nodeStates[b].getStudentWork()!="")return this.nodeStates[b].getStudentWork();return""};typeof eventManager!="undefined"&&eventManager.fire("scriptLoaded","vle/data/nodevisit.js");
if(typeof eventManager != 'undefined'){eventManager.fire('scriptLoaded', 'vle/minified/studentwork_min.js');}
