function ExplanationBuilderState(a,c,b){this.explanationIdeas=[];this.answer="";if(a!=null)this.explanationIdeas=a;if(c!=null)this.answer=c;if(b!=null)this.timestamp=b}function ExplanationIdea(a,c,b,d,e){this.id=a;this.xpos=c;this.ypos=b;this.color=d?d:"rgb(38, 84, 207)";if(e)this.lastAcceptedText=e}ExplanationBuilderState.prototype.parseDataJSONObj=function(a){return new ExplanationBuilderState(a.explanationIdeas,a.answer,a.timestamp)};ExplanationBuilderState.prototype.getStudentWork=function(){return this};
typeof eventManager!="undefined"&&eventManager.fire("scriptLoaded","vle/node/explanationbuilder/explanationbuilderstate.js");function ExplanationBuilder(a,c){this.node=a;this.view=c;this.content=a.getContent().getContentJSON();this.states=a.studentWork!=null?a.studentWork:[];this.stateChanged=this.basketChanged=!1;this.bg=this.instructions=this.question=""}
ExplanationBuilder.prototype.render=function(){var a=this.content.prompt,c=this.content.instructions,b=this.content.background;if(a!=null)this.question=a,$("#questionText").text(a);if(c!=null)this.instructions=c,$("#instructions").html(c);if(b)this.bg=b,$("#explanationIdeas").css("background-image","url("+b+")"),$("#explanationIdeas").css("background-repeat","no-repeat"),$("#explanationIdeas").css("background-position","left top");this.initializeUI()};
ExplanationBuilder.prototype.initializeUI=function(){this.ideaBasket=this.view.ideaBasket;$("#ideaDialog").dialog({title:"Add New Idea to Basket",autoOpen:!1,modal:!0,resizable:!1,width:"470",buttons:{OK:function(){if($("#ideaForm").validate().form()){var a=$("#source").val();a=="Other"&&(a="Other: "+$("#other").val());explanationBuilder.add($("#text").val(),a,$("#tags").val(),$("input[name='flag']:checked").val());$(this).dialog("close");resetForm("ideaForm")}},Cancel:function(){$(this).dialog("close");
resetForm("ideaForm")}}});$("#addNew").click(function(){$("#ideaDialog").dialog("open")});$("textarea#text, textarea#editText").keyup(function(){if(this.value.length>=150)this.value=this.value.substring(0,150)});var a=this.content.prompt,c=this.content.instructions,b=this.content.background,d=[],e="",f=this.getLatestState();this.latestState=f;if(f!=null)d=f.explanationIdeas,e=f.answer;this.load(a,c,b,d,e)};
ExplanationBuilder.prototype.getLatestState=function(){var a=null;this.states!=null&&this.states.length>0&&(a=this.states[this.states.length-1]);return a};
ExplanationBuilder.prototype.save=function(){if(this.view.ideaBasket){var a=$("#explanationText").val();if(this.latestState!=null&&this.latestState.answer!=a)this.stateChanged=!0;this.stateChanged==!0&&(a=new ExplanationBuilderState(this.explanationIdeas,$("#explanationText").val(),Date.parse(new Date)),eventManager.fire("pushStudentWork",a),this.states.push(a));if(this.basketChanged==!0)this.ideaBasket.saveIdeaBasket(this.view),this.basketChanged=!1}};
function resetForm(a){$("#"+a).validate().resetForm();$("#"+a).find(":input").each(function(){switch(this.type){case "password":case "select-multiple":case "text":case "textarea":$(this).val("")}})}
ExplanationBuilder.prototype.init=function(a){$("#save").addClass("ui-state-disabled");$("#explanationText").keyup(function(){a.answer=$("#explanationText").val();$("#save").removeClass("ui-state-disabled")});$("#save").click(function(){$(this).addClass("ui-state-disabled")});$("#target").droppable({scope:"drag-idea",activeClass:"active",drop:function(b,d){var c=d.helper.find("tr").attr("id"),c=c.replace("idea",""),f=d.helper.position(),g=f.left,f=f.top;f<1&&(f=1);g<1?g=1:g>320&&(g=320);a.stateChanged=
!0;a.addExpIdea(a,!1,!0,c,g,f)}});$("#ideasWrapper").droppable({scope:"used-idea",activeClass:"active",hoverClass:"hover",drop:function(b,d){var c=d.helper.attr("id"),c=c.replace("explanationIdea","");d.helper.hasClass("selected")&&($.each(a.selected,function(b,d){d==c&&a.selected.splice(b,1)}),a.selected.length<1&&$("#colorPicker").fadeOut());a.removeExpIdea(a,c)}});var c="";$.each(["rgb(38, 84, 207)","rgb(0, 153, 51)","rgb(204, 51, 51)","rgb(204, 102, 0)","rgb(153, 102, 255)","rgb(153, 51, 51)"],
function(a,d){c+='<div class="color" style="background-color:'+d+'"></div>'});$("#colorPicker").html(c);$(".color").click(function(){$(".color").removeClass("current");$(this).addClass("current");var b=$(this).css("background-color");$(a.selected).each(function(c,e){$("#explanationIdea"+e).css("background-color",b);a.updateExpIdea(e,null,null,b)})});$("#explanation").click(function(a){if($(a.target).attr("id")=="target"||$(a.target).attr("id")=="explanationText")$(".exIdea").removeClass("selected"),
$("#colorPicker").fadeOut()})};
ExplanationBuilder.prototype.load=function(a,c,b,d,e){if(a!=null)this.question=a,$("#questionText").text(a);if(c!=null)this.instructions=c,$("#instructions").html(c);if(b)this.bg=b,$("#explanationIdeas").css("background-image","url("+b+")"),$("#explanationIdeas").css("background-repeat","no-repeat"),$("#explanationIdeas").css("background-position","left top");if(e)this.answer=e,$("#explanationText").val(e);$("#activeIdeas tbody tr").each(function(){$(this).remove()});$(".exIdea").remove();if(this.ideaBasket==
null)this.view.authoringMode||(alert("Error: Failed to retrieve Idea Basket, you will not be able to work on this step, reload this step or refresh the VLE to try to load it again",3),$("#addNew").attr("disabled","disabled"),$("#save").attr("disabled","disabled"),$("#explanationText").attr("disabled","disabled"));else{for(a=0;a<this.ideaBasket.ideas.length;a++)this.addRow(this.ideaBasket.ideas[a],!0);if(d){for(a=0;a<d.length;a++){var c=d[a].id,b=d[a].xpos,e=d[a].ypos,f=d[a].color,g=null;d[a].lastAcceptedText?
g=d[a].lastAcceptedText:(g=this.ideaBasket.getIdeaById(c).text,d[a].lastAcceptedText=g);this.addExpIdea(this,!0,this.ideaBasket.isIdeaActive(c),c,b,e,f,g)}this.explanationIdeas=d}}$("#colorPicker").hide();$(".exIdea").removeClass("selected");this.selected=[];this.init(this)};
ExplanationBuilder.prototype.add=function(a,c,b,d){var e=this.view.getCurrentNode().id,f=this.view.getCurrentNode().getTitle(),f=this.view.getProject().getVLEPositionById(e)+": "+f,a=this.ideaBasket.addIdeaToBasketArray(a,c,b,d,e,f);this.ideaBasket.index++;this.basketChanged=!0;this.addRow(a)};
ExplanationBuilder.prototype.addRow=function(a,c){var b=a.text.replace(RegExp("(\\w{25})(?=\\w)","g"),"$1<wbr>"),b='<tr id="idea'+a.id+'" title="Click and drag to add to idea space, Double click to edit"><td>'+b+'</td><td style="text-align:center;"><span title="'+a.flag+'" class="'+a.flag+'"></span>';$("#activeIdeas tbody").prepend(b);b=$("#idea"+a.id);c||b.effect("pulsate",{times:2},500);this.makeDraggable(this,b);this.ideaBasket.ideas.length>0?$("#ideasEmpty").hide():$("#ideasEmpty").show()};
ExplanationBuilder.prototype.edit=function(a,c,b,d,e,f){for(var g,h=0;h<this.ideaBasket.ideas.length;h++)if(this.ideaBasket.ideas[h].id==a){g=this.ideaBasket.ideas[h].id;var j=$("#idea"+g);this.ideaBasket.ideas[h].text=c;this.ideaBasket.ideas[h].source=b;this.ideaBasket.ideas[h].tags=d;this.ideaBasket.ideas[h].flag=e;c=(new Date).getTime();this.ideaBasket.ideas[h].timeLastEdited=c;b=this.ideaBasket.ideas[h];c=this.ideaBasket.ideas[h].text.replace(RegExp("(\\w{25})(?=\\w)","g"),"$1<wbr>");j.html("<td>"+
c+'</td><td><span title="'+b.flag+'" class="'+b.flag+'"></span></td>');j.effect("pulsate",{times:2},500);j.hasClass("ui-draggable-disabled")&&setTimeout(function(){j.css("opacity",".5")},1200);this.basketChanged=!0;break}if(f)for(h=0;h<this.explanationIdeas.length;h++)if(this.explanationIdeas[h].id==a){this.updateExpIdea(g,null,null,null,c);break}};
ExplanationBuilder.prototype.updateOrder=function(){var a=[],c=this.ideaBasket.ideas;$("#activeIdeas tbody tr").each(function(){for(var b=$(this).attr("id"),b=b.replace("idea",""),b=parseInt(b),d=0;d<c.length;d++)if(c[d].id==b){a.push(c[d]);break}});this.ideaBasket.ideas=a};
ExplanationBuilder.prototype.makeDraggable=function(a,c){c.draggable({helper:function(a){return $('<div class="drag-idea"><table class="tablesorter" style="width:260px;"></table></div>').find("table").append($(a.target).closest("tr").clone()).end().insertAfter($("#target"))},start:function(a){$(a.target).addClass("drag")},stop:function(a){$(a.target).removeClass("drag")},cursor:"pointer",scope:"drag-idea"});c.dblclick(function(){$(this);var b=$(this).attr("id"),b=b.replace("idea",""),c="",b=parseInt(b),
c=a.populateEditForm(a,b,!0);$("#editDialog").dialog({title:"Edit Your Idea",modal:!0,resizable:!1,width:"470",buttons:{OK:function(){if($("#editForm").validate().form()){var e=!1,f=!1;$("#editText").val()!=c?(f=!0,e=a.checkIfIdeaUsed(b)):e=!0;e&&(e=$("#editSource").val(),e=="Other"&&(e="Other: "+$("#editOther").val()),a.edit(b,$("#editText").val(),e,$("#editTags").val(),$("input[name='editFlag']:checked").val(),f),$(this).dialog("close"),resetForm("editForm"))}},Cancel:function(){$(this).dialog("close");
resetForm("editForm")}}})})};
ExplanationBuilder.prototype.checkIfIdeaUsed=function(a){var c=!0,a=this.ideaBasket.getIdeaById(a).stepsUsedIn,b=!1,d=this.view.getCurrentNode().id;if(a!=null&&a.length>0){for(var e="This idea is currently used in the following steps\n\n",f=0;f<a.length;f++){var g=a[f];if(g!=d){var b=!0,h=this.view.getProject().getNodeById(g);h!=null&&(g=this.view.getProject().getVLEPositionById(g),e+=g+": "+h.title+"\n")}}e+="\nIf you change this idea, you might want to review your answers in those steps.";b&&(c=
confirm(e))}return c};
ExplanationBuilder.prototype.addExpIdea=function(a,c,b,d,e,f,g,h){$("#spacePrompt").hide();var j="",l="",k="",i=k=null,m,n="rgb(38, 84, 207)";g&&(n=g);var o=!1;if(b){for(i=0;i<this.ideaBasket.ideas.length;i++)if(this.ideaBasket.ideas[i].id==d){m=new ExplanationIdea(d,e,f,g);k="Click and drag to move; Click to change color";l=this.ideaBasket.ideas[i].text;j='<span title="'+k+'">'+l+"</span>";k=this.ideaBasket.ideas[i].timeLastEdited;i=this.ideaBasket.ideas[i].timeCreated;this.latestState!=null&&k!=
null&&i!=null&&k!=i&&h&&l!=h&&(o=!0,j+=" <img class='notification' src='/vlewrapper/vle/images/ideaManager/info.png' alt='warn' /><div class='tooltip'><div>This idea has <b>changed</b> since you added it to the explanation. What do you want to do?</div><div class='notificationLinks'><a class='notificationLink revise'>Revise</a><a class='notificationLink accept'>Keep</a></div></div>");g=a.node.id;this.addStepUsedIn(d,g);b=!0;break}$("#idea"+d).draggable("disable")}else{for(i=0;i<this.ideaBasket.deleted.length;i++)if(this.ideaBasket.deleted[i].id==
d){m=new ExplanationIdea(d,e,f,g);k="Click and drag to move";j='<span title="'+k+'">'+this.ideaBasket.deleted[i].text+"</span>";k=this.ideaBasket.deleted[i].timeLastEdited;i=this.ideaBasket.deleted[i].timeCreated;j+=" <img class='notification' src='/vlewrapper/vle/images/ideaManager/info.png' alt='warn' /><div class='tooltip'><div>You have <b>deleted</b> this idea. What do you want to do?</div><div class='notificationLinks'><a class='notificationLink restore'>Restore & Revise</a><a class='notificationLink remove'>Remove</a></div></div>";
g=a.node.id;this.addStepUsedIn(d,g);isDeleted=!0;break}n="#CCCCCC"}$(".exIdea").removeClass("selected");$("#target").append('<div class="exIdea" class="selected" id="explanationIdea'+d+'" style="position:absolute; left:'+e+"px; top:"+f+"px; background-color:"+n+'">'+j+"</div>");$("#colorPicker").show();e=300-$("#explanationIdea"+d).height();f>e&&$("#explanationIdea"+d).css("top",e);if(!c)m.lastAcceptedText=l,a.explanationIdeas.push(m);b?$("#explanationIdea"+d).dblclick(function(){$(this);var b=$(this).attr("id"),
b=b.replace("explanationIdea",""),c="",b=parseInt(b),c=a.populateEditForm(a,b,!0);$("#editDialog").dialog({title:"Edit Your Idea",modal:!0,resizable:!1,width:"470",buttons:{OK:function(){if($("#editForm").validate().form()){var d=!1,e=!1;$("#editText").val()!=c?(e=!0,d=a.checkIfIdeaUsed(b)):d=!0;d&&(d=$("#editSource").val(),d=="Other"&&(d="Other: "+$("#editOther").val()),a.edit(b,$("#editText").val(),d,$("#editTags").val(),$("input[name='editFlag']:checked").val(),e),$(this).dialog("close"),resetForm("editForm"))}},
Cancel:function(){$(this).dialog("close");resetForm("editForm")}}})}):a.bindNotificationLinks(a,!1,d,l);o&&a.bindNotificationLinks(a,!0,d,l);$("#explanationIdea"+d).click(function(b){if(!$(this).is(":animated"))if($(this).hasClass("deleted"))$("#colorPicker").hide(),$(".exIdea").removeClass("selected"),this.selected=[];else{var c=$(this).attr("id"),c=c.replace("explanationIdea",""),d=$(this).css("background-color");b.shiftKey?$(this).hasClass("selected")?($(this).removeClass("selected"),$.each(a.selected,
function(b,d){d==c&&a.selected.splice(b,1)}),a.selected.length<1?($(".exIdea").removeClass("selected"),$("#colorPicker").fadeOut()):a.selected.length==1&&$(".color").removeClass("current")):($("#colorPicker").fadeIn(),a.selected.push(c),$(this).addClass("selected"),$(".color").removeClass("current"),a.selected.length==1&&$(".color").each(function(){$(this).css("background-color")==d&&$(this).addClass("current")})):(a.selected=[c],$(".exIdea").removeClass("selected"),$(this).addClass("selected"),$("#colorPicker").fadeIn(),
$(".color").removeClass("current"),$(".color").each(function(){$(this).css("background-color")==d&&$(this).addClass("current")}))}});$("#explanationIdea"+d).draggable({scope:"used-idea",stop:function(){var b=$(this).position(),c=b.left,b=b.top,d=300-$(this).height();b>d?b=d:b<1&&(b=1);c<1?c=1:c>320&&(c=320);$(this).css("top",b+"px");$(this).css("left",c+"px");d=$(this).attr("id");d=d.replace("explanationIdea","");a.updateExpIdea(d,c,b)}});$("#explanationIdea"+d).click()};
ExplanationBuilder.prototype.updateExpIdea=function(a,c,b,d,e){this.stateChanged=!0;for(var f=0;f<this.explanationIdeas.length;f++)if(this.explanationIdeas[f].id==a){if(c)this.explanationIdeas[f].xpos=c;if(b)this.explanationIdeas[f].ypos=b;if(d)this.explanationIdeas[f].color=d;if(e)this.explanationIdeas[f].lastAcceptedText=e,$("#explanationIdea"+a).html(e);break}};
ExplanationBuilder.prototype.removeExpIdea=function(a,c){this.stateChanged=!0;for(var b=0;b<this.explanationIdeas.length;b++)if(this.explanationIdeas[b].id==c){this.explanationIdeas.splice(b,1);this.removeStepUsedIn(c,a.node.id);break}$("#explanationIdea"+c).remove();$("#idea"+c)&&($("#idea"+c).draggable("enable"),$("#idea"+c).effect("pulsate",{times:2},500));a.explanationIdeas.length<1&&$("#spacePrompt").show()};
ExplanationBuilder.prototype.bindNotificationLinks=function(a,c,b,d){function e(){$("#explanationIdea"+b+" .tooltip").fadeOut("medium",function(){$("#explanationIdea"+b+" .tooltip").remove()});$("#explanationIdea"+b+" .notification").fadeOut("medium",function(){$("#explanationIdea"+b+" .notification").remove()})}$("#explanationIdea"+b+" img").tooltip({relative:!0,offset:[8,0]}).dynamic({bottom:{direction:"down"}});c?($("#explanationIdea"+b+" a.revise").click(function(){var c=a.populateEditForm(a,
b,!0);$("#editDialog").dialog({title:"Revise Your Idea",modal:!0,resizable:!1,width:"470",buttons:{OK:function(){if($("#editForm").validate().form()){var d=!1;if(d=$("#editText").val()!=c?a.checkIfIdeaUsed(b):!0)d=$("#editSource").val(),d=="Other"&&(d="Other: "+$("#editOther").val()),a.edit(b,$("#editText").val(),d,$("#editTags").val(),$("input[name='editFlag']:checked").val(),!0),$(this).dialog("close"),resetForm("editForm")}},Cancel:function(){$(this).dialog("close");resetForm("editForm")}}})}),
$("#explanationIdea"+b+" a.accept").click(function(){for(var c=b,g=0;g<a.explanationIdeas.length;g++)if(a.explanationIdeas[g].id==c)a.explanationIdeas[g].lastAcceptedText=d;e()})):($("#explanationIdea"+b).addClass("deleted"),$("#explanationIdea"+b+" a.restore").click(function(){a.populateEditForm(a,b,!1);$("#editDialog").dialog({title:"Revise Your Idea",modal:!0,resizable:!1,width:"470",buttons:{OK:function(){var c=$("#editSource").val();c=="Other"&&(c="Other: "+$("#editOther").val());var d=a.putBack(b);
a.edit(b,$("#editText").val(),c,$("#editTags").val(),$("input[name='editFlag']:checked").val(),!0);setTimeout(function(){$("#idea"+b).css("opacity",".5")},1200);$("#explanationIdea"+b).css("background-color",d);$("#explanationIdea"+b).removeClass("deleted");$("#idea"+b).draggable("disable");resetForm("editForm");$(this).dialog("close")},Cancel:function(){$(this).dialog("close");resetForm("editForm")}}})}),$("#explanationIdea"+b+" a.remove").click(function(){a.removeExpIdea(a,b)}))};
ExplanationBuilder.prototype.addStepUsedIn=function(a,c){var b=this.ideaBasket.getIdeaById(a);if(b!=null){var d=b.stepsUsedIn;if(d==null)b.stepsUsedIn=[],d=b.stepsUsedIn;for(var b=!1,e=0;e<d.length;e++)d[e]==c&&(b=!0);if(!b)d.push(c),this.basketChanged=!0}};
ExplanationBuilder.prototype.removeStepUsedIn=function(a,c){var b=this.ideaBasket.getIdeaById(a);if(b!=null){var d=b.stepsUsedIn;if(d==null)b.stepsUsedIn=[],d=b.stepsUsedIn;for(b=0;b<d.length;b++)if(d[b]==c)d.splice(b,1),b--,this.basketChanged=!0}};
ExplanationBuilder.prototype.putBack=function(a){for(var c=0;c<this.ideaBasket.deleted.length;c++)if(this.ideaBasket.deleted[c].id==a){this.ideaBasket.ideas.splice(0,0,this.ideaBasket.deleted[c]);var b=this.ideaBasket.deleted[c],d=(new Date).getTime();b.timeLastEdited=d;this.ideaBasket.deleted.splice(c,1);this.addRow(b,!0);break}for(c=0;c<this.explanationIdeas.length;c++)if(this.explanationIdeas[c].id==a){var e=this.explanationIdeas[c].color;break}this.basketChanged=!0;this.ideaBasket.updateToolbarCount(!0);
return e};
ExplanationBuilder.prototype.populateEditForm=function(a,c,b){for(var d=b?a.ideaBasket.ideas:a.ideaBasket.deleted,e=0;e<d.length;e++)if(d[e].id==c){text=d[e].text;$("#editText").val(text);d[e].source.match(/^Other: /)?($("#editSource").val("Other"),$("#editOther").val(d[e].source.replace(/^Other: /,"")),$("#editOtherSource").show(),$("#editOther").addClass("required")):($("#editSource").val(d[e].source),$("#editOtherSource").hide(),$("#editOther").removeClass("required"));$("#editTags").val(d[e].tags);$("input[name='editFlag']").each(function(){$(this).attr("value")==
d[e].flag?$(this).attr("checked",!0):$(this).attr("checked",!1)});break}return text};ExplanationBuilder.prototype.ideaBasketChanged=function(a){this.ideaBasket=a;this.load(this.question,this.instructions,this.bg,this.explanationIdeas,this.answer)};typeof eventManager!="undefined"&&eventManager.fire("scriptLoaded","vle/node/explanationbuilder/explanationBuilder.js");
if(typeof eventManager != 'undefined'){eventManager.fire('scriptLoaded', 'vle/node/explanationbuilder/explanationbuilder_grading_min.js');}
