function TableState(a,b){this.response="";this.tableData=[];if(a!=null)this.response=a;if(b!=null)this.tableData=b}TableState.prototype.parseDataJSONObj=function(a){return new TableState(a.response,a.tableData)};TableState.prototype.getStudentWork=function(){return this};
TableState.prototype.getTableHtml=function(){var a=0,b=0,b=this.tableData[0];if(b!=null)a=b.length;var b=this.tableData.length,c="";c+="<table style='border-width:1px; border-style:outset'>";for(var d=0;d<a;d++){c+="<tr>";for(var f=0;f<b;f++){c+="<td style='border-width:1px; border-style:inset; width:20px; height:20px'>";if(this.tableData!=null&&this.tableData[f]!=null&&this.tableData[f][d]!=null&&this.tableData[f][d].text!=null){var e=this.tableData[f][d].text;if(e==null||e=="")e="&nbsp";c+=e}c+=
"</td>"}c+="</tr>"}c+="</table>";return c};typeof eventManager!="undefined"&&eventManager.fire("scriptLoaded","vle/node/table/tablestate.js");function Table(a,b){this.node=a;this.view=b;this.content=a.getContent().getContentJSON();this.states=a.studentWork!=null?a.studentWork:[];this.responseChanged=this.tableChanged=!1}
Table.prototype.render=function(){$("#promptDiv").html(this.content.prompt);for(var a=document.createElement("table"),b=this.content.tableData,c=this.getLatestState(),d=0;d<this.content.numRows;d++){for(var f=document.createElement("tr"),e=0;e<this.content.numColumns;e++){var i=document.createElement("td"),h=b[e][d],j=h.text,h=h.uneditable;if(c!=null&&c.tableData!=null&&c.tableData[e]!=null&&c.tableData[e][d]!=null)j=c.tableData[e][d].text;var g=document.createElement("input");g.id="tableCell_"+e+
"-"+d;g.name="tableCell_"+e+"-"+d;g.value=j;g.size=10;g.onchange=studentTableChanged;if(h)g.disabled=!0;i.appendChild(g);f.appendChild(i)}a.appendChild(f)}$("#tableDiv").html("");$("#tableDiv").append(a);c=this.getLatestState();if(c!=null)a=c.response,$("#studentResponseTextArea").val(a)};Table.prototype.getLatestState=function(){var a=null;this.states!=null&&this.states.length>0&&(a=this.states[this.states.length-1]);return a};
Table.prototype.save=function(){if(this.responseChanged||this.tableChanged){var a=$("#studentResponseTextArea").val(),b=this.getStudentTableData(),a=new TableState(a,b);eventManager.fire("pushStudentWork",a);this.states.push(a)}this.responseChanged=this.tableChanged=!1};
Table.prototype.getStudentTableData=function(){for(var a=JSON.parse(JSON.stringify(this.content.tableData)),b=0;b<this.content.numColumns;b++)for(var c=0;c<this.content.numRows;c++){var d=$("#tableCell_"+b+"-"+c).val();a[b][c].text=d}return a};Table.prototype.reset=function(){for(var a=0;a<this.content.numColumns;a++)for(var b=0;b<this.content.numRows;b++)$("#tableCell_"+a+"-"+b).val(this.content.tableData[a][b].text);this.studentTableChanged()};
Table.prototype.studentTableChanged=function(){this.tableChanged=!0};Table.prototype.studentResponseChanged=function(){this.responseChanged=!0};typeof eventManager!="undefined"&&eventManager.fire("scriptLoaded","vle/node/table/table.js");
if(typeof eventManager != 'undefined'){eventManager.fire('scriptLoaded', 'vle/node/table/table_grading_min.js');}
