function Annotations(){this.annotationsArray=[]}Annotations.prototype.addAnnotation=function(a){this.annotationsArray.push(a)};Annotations.prototype.updateOrAddAnnotation=function(a){for(var b=!1,c=0;c<this.annotationsArray.length;c++){var d=this.annotationsArray[c];if(d.runId==a.runId&&d.nodeId==a.nodeId&&d.toWorkgroup==a.toWorkgroup&&d.fromWorkgroup==a.fromWorkgroup&&d.type==a.type){this.annotationsArray.splice(c,1);this.addAnnotation(a);b=!0;break}}b||this.addAnnotation(a)};
Annotations.prototype.removeAnnotation=function(a,b,c,d,e){for(var f=0;f<this.annotationsArray.length;f++){var g=this.annotationsArray[f];g.runId==a&&g.nodeId==b&&g.toWorkgroup==c&&g.fromWorkgroup==d&&g.studentWork==e&&this.annotationsArray.splice(f,1)}};Annotations.prototype.removeFlagAnnotation=function(a,b,c,d){for(var e=0;e<this.annotationsArray.length;e++){var f=this.annotationsArray[e];f.runId==a&&f.nodeId==b&&f.toWorkgroup==c&&f.fromWorkgroup==d&&this.annotationsArray.splice(e,1)}};
Annotations.prototype.parseDataJSONString=function(a){a=$.parseJSON(a);return Annotations.prototype.parseDataJSONObj(a)};Annotations.prototype.parseDataJSONObj=function(a){var b=new Annotations;b.annotationsArray=[];if(a.annotationsArray!=null)for(var c=0;c<a.annotationsArray.length;c++){var d=Annotation.prototype.parseDataJSONObj(a.annotationsArray[c]);b.annotationsArray.push(d)}return b};
Annotations.prototype.getLatestAnnotationForNodeId=function(a){for(var b=null,c=0;c<this.annotationsArray.length;c++)tempAnnotation=this.annotationsArray[c],tempAnnotation.nodeId==a&&(b=tempAnnotation);return b};Annotations.prototype.getAnnotationsByNodeId=function(a){for(var b=[],c=0;c<this.annotationsArray.length;c++){var d=this.annotationsArray[c];d.nodeId==a&&b.push(d)}return b};
Annotations.prototype.getAnnotationsByToWorkgroup=function(a){for(var b=[],c=0;c<this.annotationsArray.length;c++){var d=this.annotationsArray[c];d.toWorkgroup==a&&b.push(d)}return b};Annotations.prototype.getAnnotationsByToWorkgroupAndFromWorkgroups=function(a,b){for(var c=[],d=0;d<this.annotationsArray.length;d++){var e=this.annotationsArray[d];e.toWorkgroup==a&&b.indexOf(parseInt(e.fromWorkgroup))!=-1&&c.push(e)}return c};
Annotations.prototype.getTotalScoreByToWorkgroup=function(a){for(var a=this.getAnnotationsByToWorkgroup(a),b=0,c=0;c<a.length;c++)a[c].type=="score"&&(b+=parseFloat(a[c].value));return b};Annotations.prototype.getTotalScoreByToWorkgroupAndFromWorkgroups=function(a,b){return this.getTotalScoreAndTotalPossibleByToWorkgroupAndFromWorkgroups(a,b,null).totalScore};
Annotations.prototype.getTotalScoreAndTotalPossibleByToWorkgroupAndFromWorkgroups=function(a,b,c){for(var d={},e=this.getAnnotationsByToWorkgroupAndFromWorkgroups(a,b),b=a=0,f={},g=[],i=0;i<e.length;i++){var h=e[i];if(e[i].type=="score"){var j=e[i].nodeId,k=f[j];k?k.postTime<h.postTime&&(f[j]=h):(f[j]=h,g.push(j))}}for(e=0;e<g.length;e++)i=g[e],h=f[i],h!=null&&h.value!=null&&h.value!=""&&!isNaN(h.value)&&(a+=parseFloat(h.value),c!=null&&(b+=parseFloat(c.getMaxScoreValueByNodeId(i))));d.totalScore=
a;d.totalPossible=b;return d};Annotations.prototype.getAnnotationsByNodeIdAndToWorkgroup=function(a,b){for(var c=[],d=0;d<this.annotationsArray.length;d++){var e=this.annotationsArray[d];e.nodeId==a&&e.toWorkgroup==b&&c.push(e)}return c};
Annotations.prototype.getLatestAnnotation=function(a,b,c,d,e,f){for(var g=null,i=0;i<this.annotationsArray.length;i++){var h=this.annotationsArray[i];if(h.runId==a&&h.nodeId==b&&h.toWorkgroup==c&&d.indexOf(parseInt(h.fromWorkgroup))!=-1&&h.type==e&&(f==null||f!=null&&h.stepWorkId==f))g?g.postTime<h.postTime&&(g=h):g=h}return g};Annotations.prototype.getAnnotationsByFromWorkgroup=function(a){for(var b=[],c=0;c<this.annotationsArray.length;c++){var d=this.annotationsArray[c];d.fromWorkgroup==a&&b.push(d)}return b};
Annotations.prototype.getAnnotationsByType=function(a){for(var b=[],c=0;c<this.annotationsArray.length;c++){var d=this.annotationsArray[c];d.type==a&&b.push(d)}return b};Annotations.prototype.getLatestAnnotationByAll=function(a,b,c,d,e){for(var f=null,g=this.annotationsArray.length-1;g>=0;g--)if(f=this.annotationsArray[g],f.runId==a&&f.nodeId==b&&f.toWorkgroup==c&&f.fromWorkgroup==d&&f.type==e)break;return f};
Annotations.prototype.getAnnotationByStepWorkIdType=function(a,b){for(var c=null,d=this.annotationsArray.length-1;d>=0;d--)if(c=this.annotationsArray[d],c.stepWorkId==a&&c.type==b)return c;return null};Annotations.prototype.annotationsAfterDate=function(a){for(var b=this.annotationsArray.length-1;b>=0;b--){var c=this.annotationsArray[b];if(c!=null&&c.type!="flag"&&c.postTime>a)return!0}return!1};
Annotations.prototype.getNodeIds=function(){for(var a=[],b=0;b<this.annotationsArray.length;b++){var c=this.annotationsArray[b];if(c!=null)c=c.nodeId,a.indexOf(c)==-1&&a.push(c)}return a};typeof eventManager!="undefined"&&eventManager.fire("scriptLoaded","vle/grading/Annotations.js");function Annotation(a,b,c,d,e,f,g,i){this.runId=a;this.nodeId=b;this.toWorkgroup=c;this.fromWorkgroup=d;this.type=e;this.value=f;this.postTime=g;this.stepWorkId=i}Annotation.prototype.parseDataJSONString=function(a){a=$.parseJSON(a);return Annotation.prototype.parseDataJSONObj(a)};
Annotation.prototype.parseDataJSONObj=function(a){var b=new Annotation;b.runId=a.runId;b.nodeId=a.nodeId;b.toWorkgroup=a.toWorkgroup;b.fromWorkgroup=a.fromWorkgroup;b.type=a.type;b.value=a.value;b.postTime=a.postTime;b.stepWorkId=a.stepWorkId;if(a.data)b.data=NODE_VISIT.prototype.parseDataJSONObj(a.data);if(a.annotationComment)b.annotationComment=Annotation.prototype.parseDataJSONObj(a.annotationComment);return b};typeof eventManager!="undefined"&&eventManager.fire("scriptLoaded","vle/grading/Annotation.js");
if(typeof eventManager != 'undefined'){eventManager.fire('scriptLoaded', 'vle/minified/annotations_min.js');}
