View.prototype.gradingDispatcher=function(a,b,c){if(a=="displayGradeByStepGradingPage")c.displayGradeByStepGradingPage(b[0],b[1]);else if(a=="displayGradeByTeamGradingPage")c.displayGradeByTeamGradingPage(b[0]);else if(a=="displayResearcherToolsPage")c.displayResearcherToolsPage();else if(a=="displayCustomExportPage")c.displayCustomExportPage();else if(a=="saveScore")c.checkAndSaveScore(b[0],b[1],b[2],b[3],b[4]);else if(a=="saveComment")c.saveComment(b[0],b[1],b[2],b[3],b[4],b[5]);else if(a=="saveFlag")c.saveFlag(b[0],
b[1],b[2],b[3],b[4],b[5]);else if(a=="processUserAndClassInfoComplete")c.getProjectMetaData();else if(a=="gradingConfigUrlReceived")c.getGradingConfig(b[0]);else if(a=="getGradingConfigComplete")c.retrieveLocales(),c.loadProject(b[0],b[1],b[2]),c.initializeSession();else if(a=="loadingProjectComplete")c.getStudentUserInfo(),c.checkAndMinify();else if(a=="getAllStudentWorkXLSExport")c.getAllStudentWorkXLSExport();else if(a=="getLatestStudentWorkXLSExport")c.getLatestStudentWorkXLSExport();else if(a==
"getIdeaBasketsExcelExport")c.getIdeaBasketsExcelExport();else if(a=="getExplanationBuilderWorkExcelExport")c.getExplanationBuilderWorkExcelExport();else if(a=="getCustomLatestStudentWorkExport")c.getCustomLatestStudentWorkExport();else if(a=="getCustomAllStudentWorkExport")c.getCustomAllStudentWorkExport();else if(a=="customActivityCheckBoxClicked")c.customActivityCheckBoxClicked(b[0]);else if(a=="customSelectAllStepsCheckBoxClicked")c.customSelectAllStepsCheckBoxClicked();else if(a=="getStudentNamesExport")c.getStudentNamesExport();
else if(a=="getProjectMetaDataComplete")c.getAnnotations();else if(a=="saveMaxScore")c.saveMaxScore(b[0],b[1]);else if(a=="showScoreSummary")c.showScoreSummary();else if(a=="filterPeriod")c.filterPeriod(b[0],b[1]);else if(a=="displayGradeByStepSelectPage")c.displayGradeByStepSelectPage();else if(a=="displayGradeByTeamSelectPage")c.displayGradeByTeamSelectPage();else if(a=="displayStudentUploadedFiles")c.displayStudentUploadedFiles();else if(a=="togglePrompt")c.togglePrompt(b[0]);else if(a=="refreshGradingScreen")c.refreshGradingScreen();
else if(a=="smartFilter")c.smartFilter();else if(a=="getAnnotationsComplete")c.getIdeaBaskets();else if(a=="getIdeaBasketsComplete")eventManager.fire("projectDataReceived"),c.initiateGradingDisplay();else if(a=="getStudentWorkComplete")c.calculateGradingStatistics(),c.reloadRefreshScreen();else if(a=="toggleGradingDisplayRevisions")c.toggleGradingDisplayRevisions(b[0],b[1]);else if(a=="toggleAllGradingDisplayRevisions")c.toggleAllGradingDisplayRevisions(b[0]);else if(a=="onlyShowFilteredItemsOnClick")c.onlyShowFilteredItemsOnClick();
else if(a=="onlyShowWorkOnClick")c.onlyShowWorkOnClick();else a=="filterStudentRows"?c.filterStudentRows():a=="enlargeStudentWorkText"?c.enlargeStudentWorkText():a=="openPremadeComments"?c.openPremadeComments(b[0],b[1]):a=="selectPremadeComment"?c.selectPremadeComment(b[0]):a=="submitPremadeComment"?c.submitPremadeComment():a=="premadeCommentWindowLoaded"?c.premadeCommentWindowLoaded():a=="addPremadeComment"?c.addPremadeComment(b[0]):a=="deletePremadeComment"?c.deletePremadeComment(b[0],b[1]):a==
"displayExportExplanation"?c.displayExportExplanation(b[0]):a=="setSelectedPeriod"&&c.setSelectedPeriod(b[0])};typeof eventManager!="undefined"&&eventManager.fire("scriptLoaded","vle/view/grading/gradingview_dispatcher.js");View.prototype.getAllStudentWorkXLSExport=function(){this.setParamsForXLSExport();document.getElementById("exportType").value="allStudentWork";document.getElementById("getStudentXLSExport").submit()};View.prototype.getLatestStudentWorkXLSExport=function(){this.setParamsForXLSExport();document.getElementById("exportType").value="latestStudentWork";document.getElementById("getStudentXLSExport").submit()};
View.prototype.getIdeaBasketsExcelExport=function(){this.setParamsForXLSExport();document.getElementById("exportType").value="ideaBaskets";document.getElementById("getStudentXLSExport").submit()};View.prototype.getExplanationBuilderWorkExcelExport=function(){this.setParamsForXLSExport();document.getElementById("exportType").value="explanationBuilderWork";document.getElementById("getStudentXLSExport").submit()};
View.prototype.getCustomLatestStudentWorkExport=function(){this.setParamsForXLSExport();$("#exportType").val("customLatestStudentWork");var a=this.getCustomStepsArrayJSONString();$("#customStepsArray").val(a);$("#getStudentXLSExport").submit()};View.prototype.getCustomAllStudentWorkExport=function(){this.setParamsForXLSExport();$("#exportType").val("customAllStudentWork");var a=this.getCustomStepsArrayJSONString();$("#customStepsArray").val(a);$("#getStudentXLSExport").submit()};
View.prototype.getStudentNamesExport=function(){var a=this.getConfig().getConfigParam("getStudentListUrl");document.getElementById("runId").value=this.getConfig().getConfigParam("runId");document.getElementById("getStudentXLSExport").action=a;$("#getStudentXLSExport").submit()};View.prototype.getCustomStepsArrayJSONString=function(){var a="",b=this.getCustomStepsArray();b!=null&&(a=JSON.stringify(b));return a};
View.prototype.getCustomStepsArray=function(){for(var a=[],b=$("input:checkbox[name='customExportStepCheckbox']:checked"),c=0;c<b.length;c++){var d=b[c];if(d!=null)d=d.value,d!=null&&a.push(d)}return a};View.prototype.getNodeIdToNodeTitlesMap=function(a){if(a.isLeafNode())this.nodeIdToNodeTitleArray.push((a.id+"###58;"+this.getProject().getVLEPositionById(a.id)+" "+a.title).replace(/,/g,"###44;"));else for(var b=0;b<a.children.length;b++)this.getNodeIdToNodeTitlesMap(a.children[b])};
View.prototype.setParamsForXLSExport=function(){document.getElementById("runId").value=this.getConfig().getConfigParam("runId");document.getElementById("projectId").value=this.getConfig().getConfigParam("projectId");document.getElementById("parentProjectId").value=this.getConfig().getConfigParam("parentProjectId");document.getElementById("runName").value=this.getConfig().getConfigParam("runName");document.getElementById("projectName").value=this.project.getTitle();document.getElementById("projectPath").value=
this.getConfig().getConfigParam("getProjectPath");document.getElementById("type").value="xlsexport";document.getElementById("getStudentXLSExport").action=this.getConfig().getConfigParam("getXLSExportUrl")};View.prototype.showScores=function(){for(var a=this.getUserAndClassInfo().vle.myClassInfo.classmates,b="score\tname\n",c=0;c<a.length;c++){var d=a[c],e=annotations.getTotalScoreByToWorkgroup(d.workgroupId);b+=e+"\t"+d.userName+"\n"}alert(b)};
View.prototype.getWorkgroupExportExplanations=function(){return this.getExplanationTRs([{label:"Workgroup Id",explanation:"the number id of the workgroup"},{label:"Wise Id 1",explanation:"the number id of the first member of the group. this id is tied directly to the student account."},{label:"Wise Id 2",explanation:"the number id of the second member of the group (if applicable). this id is tied directly to the student account."},{label:"Wise Id 3",explanation:"the number id of the third member of the group (if applicable). this id is tied directly to the student account."},
{label:"Class Period",explanation:"the period the workgroup is in"}])};
View.prototype.getRunExportExplanations=function(){return this.getExplanationTRs([{label:"Teacher Login",explanation:"the login of the teacher who created the run"},{label:"Project Id",explanation:"the id of the project"},{label:"Parent Project Id",explanation:"the id of the project that this project was copied from (if applicable)"},{label:"Project Name",explanation:"the name of the project"},{label:"Run Id",explanation:"the id of the run"},{label:"Run Name",explanation:"the name of the run"},{label:"Start Date",
explanation:"the date the run was created"},{label:"End Date",explanation:"the date the run was archived (if applicable)"}])};
View.prototype.getLatestStudentWorkExportExplanations=function(){return this.getExplanationTRs([{label:"Step Title",explanation:"the title of the step"},{label:"Step Type",explanation:"the type of the step"},{label:"Step Prompt",explanation:"the prompt that the student reads on the step"},{label:"Node Id",explanation:"the id of the step which is unique within the project"},{label:"Step Extra",explanation:"extra information about that step (*the remaining rows below are some values that you may see in the Step Extra row)"},
{label:"*Teacher Score Timestamp",explanation:"the timestamp when the teacher gave the score"},{label:"*Teacher Score",explanation:"the score from the teacher"},{label:"*Teacher Comment Timestamp",explanation:"the timestamp when the teacher gave the comment"},{label:"*Teacher Comment",explanation:"the comment from the teacher"},{label:"*Workgroup I am writing feedback to",explanation:"this step is the second step in a peer/teacher review sequence"},{label:"*Work from other workgroup",explanation:"this step is the second step in a peer/teacher review sequence"},
{label:"*Workgroup that is writing feedback to me",explanation:"this step is the third step in a peer/teacher review sequence"},{label:"*Feedback from workgroup",explanation:"this step is the third step in a peer/teacher review sequence"},{label:"*Work that I have revised based on feedback",explanation:"this step is the third step in a peer/teacher review sequence"},{label:"*(other)",explanation:"for AssessmentList steps, this will display the prompt for each of the separate parts in the AssessmentList step"}])};
View.prototype.getAllStudentWorkExportExplanations=function(){return this.getExplanationTRs([{label:"#",explanation:"the step visit counter"},{label:"Wise Id 1",explanation:"the number id of the first member of the group. if the student was absent it will say 'Absent' after the number."},{label:"Wise Id 2",explanation:"the number id of the second member of the group (if applicable). if the student was absent it will say 'Absent' after the number."},{label:"Wise Id 3",explanation:"the number id of the third member of the group (if applicable). if the student was absent it will say 'Absent' after the number."},
{label:"Step Title",explanation:"the title of the step"},{label:"Step Type",explanation:"the type of the step"},{label:"Step Prompt",explanation:"the prompt that the student reads on the step"},{label:"Node Id",explanation:"the id of the step which is unique within the project"},{label:"Start Time",explanation:"the timestamp when the student entered the step"},{label:"End Time",explanation:"the timestamp when the student exited the step"},{label:"Time Spent (Seconds)",explanation:"the amount of time the student spent on the step"},
{label:"Teacher Score Timestamp",explanation:"the timestamp when the teacher gave the score"},{label:"Teacher Score",explanation:"the score from the teacher"},{label:"Teacher Comment Timestamp",explanation:"the timestamp when the teacher gave the comment"},{label:"Teacher Comment",explanation:"the comment from the teacher"},{label:"Classmate Id",explanation:"the id of the workgroup that this student is receiving text from (only applies for review sequence steps)"},{label:"Receiving Text",explanation:"the text received from the classmate (only applies for review sequence steps)"},
{label:"Student Work or Student Work Part 1",explanation:"the work the student submitted for this step"},{label:"Student Work Part 2 (if applicable)",explanation:"the second part of the work the student submitted for this step (only applies to steps that have multiple parts such as AssessmentList)"},{label:"Student Work Part N (if applicable)",explanation:"the Nth part of the work the student submitted for this step (only applies to steps that have multiple parts such as AssessmentList)"}])};
View.prototype.getIdeaBasketsExportExplanations=function(){return this.getExplanationTRs([{label:"Basket Revision",explanation:"the revision number of the basket. each time the student makes a change to the basket, the revision number is incremented."},{label:"Idea #",explanation:"the number of the idea within the basket. the idea number for an idea never changes even if the idea text is changed or the idea is repositioned within the basket."},{label:"Idea Text",explanation:"the text student entered for the idea"},
{label:"Flag",explanation:"the flag the student chose for the idea"},{label:"Tags",explanation:"the tags the student entered for the idea"},{label:"Source",explanation:"the source the student chose for the idea"},{label:"Node Type",explanation:"the step type the student created the idea on"},{label:"Node Id Created On",explanation:"the id of the step the student created the idea on"},{label:"Node Name Created On",explanation:"the name of the step the student created the idea on"},{label:"Steps Used In Count",
explanation:"the number of steps this idea is used in (such as explanation builder steps)"},{label:"Steps Used In",explanation:"the list of steps that this idea is used in (the ideas are comma delimited in this format nodeId:nodeTitle, nodeId:nodeTitle, ...)"},{label:"Trash",explanation:"whether the idea is in the trash (0 if no, 1 if yes)"},{label:"Timestamp Basket Saved",explanation:"the timestamp when this basket revision was saved"},{label:"Timestamp Idea Created",explanation:"the timestamp when this idea was created"},
{label:"Timestamp Idea Last Edited",explanation:"the timestamp when this idea was last edited"},{label:"New",explanation:"whether the idea is new in this basket revision (0 if no, 1 if yes)"},{label:"Revised",explanation:"whether the idea was changed in this basket revision (0 if no, 1 if yes)"},{label:"Repositioned",explanation:"whether the position of this idea was changed within the basket in this basket revision (0 if no, 1 if yes)"},{label:"Steps Used In Changed",explanation:"whether the idea was either used or removed from a step in this basket revision (such as an explanation builder step) (0 if no, 1 if yes)"},
{label:"Deleted In This Revision",explanation:"whether the idea was placed in the trash in this basket revision (0 if no, 1 if yes)"}])};
View.prototype.getExplanationBuilderWorkExportExplanations=function(){return this.getExplanationTRs([{label:"Step Work Id",explanation:"the id of the student work"},{label:"Step Title",explanation:"the title of the step"},{label:"Step Prompt",explanation:"the prompt of the step"},{label:"Node Id",explanation:"the id of the step"},{label:"Start Time",explanation:"the timestamp the student entered the step"},{label:"End Time",explanation:"the timestamp the student exited the step"},{label:"Time Spent (in seconds)",
explanation:"the time the student spent on the step"},{label:"Answer",explanation:"the text the student entered into the bottom textarea in the explanation builder step"},{label:"Idea Id",explanation:"the id of the idea within the idea basket"},{label:"Idea Text",explanation:"the text the student wrote for this idea"},{label:"Idea X Position",explanation:"the x position of the upper left corner of the idea rectangle relative to the upper left corner of the background image"},{label:"Idea Y Position",
explanation:"the y position of the upper left corner of the idea rectangle relative to the upper left corner of the background image"},{label:"Idea Color",explanation:"the color the student chose for the idea"}])};
View.prototype.getStudentNamesExportExplanations=function(){return this.getExplanationTRs([{label:"Period",explanation:"the period the student is in"},{label:"Workgroup Id",explanation:"the id of the workgroup"},{label:"Wise Id",explanation:"the id of the student"},{label:"Student Username",explanation:"the login username of the student"},{label:"Student Name",explanation:"the name of the name of the student"}])};
View.prototype.getExplanationTRs=function(a){for(var b="",c=0;c<a.length;c++){var d=a[c],e=d.label,d=d.explanation;b+="<tr>";b+=this.getExplanationTD(e)+this.getExplanationTD(d);b+="</tr>"}return b};View.prototype.getExplanationTD=function(a){var b="";b+="<td class='exportExplanationTd'>";b+=a;b+="</td>";return b};
function refresh(){lock();render(this.contentURL,this.userURL,this.getDataUrl,this.contentBaseUrl,this.getAnnotationsUrl,this.postAnnotationsUrl,this.runId,this.getFlagsUrl,this.postFlagsUrl)}function exportGrades(a){displayExportData(a);vle.saveStudentWorkToFile(a)}var myMenu;
function displayExportData(a){var b=window.open("","exportData","width=600,height=400"),c=vle.getContentForFile(a),a="<p>If you were asked to save the file you can ignore and close this window.</p>";a+="<p>If you were not asked to save the file, you can copy the contents in the box below and paste it into Notepad or Textedit and save it yourself.</p>";c="<textarea rows='15' cols='70'>"+c+"</textarea>";b.document.open();b.document.write(a+c);b.document.close()}
typeof eventManager!="undefined"&&eventManager.fire("scriptLoaded","vle/view/grading/gradingview_export.js");View.prototype.getGradingConfig=function(a){this.config=this.createConfig(createContent(a));eventManager.fire("getGradingConfigComplete",[this.config.getConfigParam("getContentUrl"),this.config.getConfigParam("getContentBaseUrl"),!1]);a=window.location.toString();this.minifierUrl=a.substring(0,a.lastIndexOf("/vlewrapper/vle/"))+"/webapp/router.html"};
View.prototype.getStudentUserInfo=function(){this.loadUserAndClassInfo(createContent(this.config.getConfigParam("getUserInfoUrl")));teacherId=this.getUserAndClassInfo().getWorkgroupId();this.studentWorkgroupIds=[];classUsers=this.getUserAndClassInfo().getUsersInClass();for(var a=0;a<classUsers.length;a++)classUsers[a].workgroupId!=teacherId&&this.studentWorkgroupIds.push(classUsers[a].workgroupId);eventManager.fire("processUserAndClassInfoComplete")};
View.prototype.checkAndMinify=function(){!this.isLoadedProjectMinified&&this.getProject()&&this.getConfig()&&this.getConfig().getConfigParam("getProjectPath")&&this.connectionManager.request("POST",1,this.minifierUrl,{forward:"minifier",projectId:this.getConfig().getConfigParam("projectId"),runId:this.getConfig().getConfigParam("runId"),command:"minifyProject",path:this.getConfig().getConfigParam("getProjectPath")},function(a,b,c){a=parseInt(a);isNaN(a)||(a={projectId:c.getConfig().getConfigParam("projectId"),
command:"postLastMinified",lastMinified:a},c.connectionManager.request("POST",1,c.getConfig().getConfigParam("projectMetaDataUrl"),a,function(){},this,function(){}))},this,function(){})};var studentWorkQueryObject;function afterScriptsLoad(){render(contentUrl,userUrl,getDataUrl,contentBaseUrl,getAnnotationsUrl,postAnnotationsUrl,runId)}
window.onload=function(){lock();if(window.location.search.indexOf("loadScriptsIndividually")!=-1)scriptloader.useDeflatedScripts=!1;scriptloader.initialize(document,afterScriptsLoad,"gradebystep")};View.prototype.onWindowUnload=function(){this.xmpp&&this.isXMPPEnabled&&this.xmpp.disconnect()};function projectSummary(){window.open("/webapp/student/vle/vle.html?runId="+runId+"&summary=true","Project Summary","height=600, width=800")}var newWin=null;
function popUp(a,b,c,d){newWin!=null&&!newWin.closed&&newWin.close();var e="";b=="console"&&(e="resizable,height="+c+",width="+d);b=="fixed"&&(e="status,height="+c+",width="+d);b=="elastic"&&(e="toolbar,menubar,scrollbars,resizable,location,height="+c+",width="+d);newWin=window.open(a,"newWin",e);newWin.focus()}
function load_old(a,b,c,d,e,f,g,h,j){this.contentUrl=a;this.userUrl=b;this.getDataUrl=c;this.contentBaseUrl=d;this.getAnnotationsUrl=e;this.postAnnotationsUrl=f;this.runId=g;this.getFlagsUrl=h;this.postFlagsUrl=j}var waitingIntervalId=0;function addDot(){document.getElementById("gradeWorkDiv").innerHTML+="."}function lock(){waitingIntervalId=setInterval("addDot()",1E3)}function unlock(){document.getElementById("gradeWorkDiv").innerHTML+="";clearInterval(waitingIntervalId)}
function expandMenu(a){myMenu.expandMenu(document.getElementById(a))}function render(a,b,c,d,e,f,g){vle=new VLE(!0);vle.runId=g;vle.loadProject(contentUrl,d);getStudentUserInfo();vle.eventManager.addEvent("getStudentUserInfoComplete");vle.eventManager.addEvent("getStudentWorkComplete");vle.eventManager.addEvent("getAnnotationsComplete");vle.eventManager.subscribe("getStudentUserInfoComplete",initiateDisplaySteps)}typeof eventManager!="undefined"&&eventManager.fire("scriptLoaded","vle/view/grading/gradingview_startup.js");View.prototype.saveScore=function(a,b,c,d,e){if(e=="null")alert("You are trying to grade a work that has not yet been submitted.  We currently do not support this feature.");else{var f=document.getElementById("annotationScoreTextArea_"+b+"_"+a).value,g=this.getUserAndClassInfo().getAllTeacherWorkgroupIds();isNaN(f)?(alert("Please enter a number"),c=this.annotations.getLatestAnnotation(d,a,b,g,"score"),c!=null?document.getElementById("annotationScoreTextArea_"+b+"_"+a).value=c.value:document.getElementById("annotationScoreTextArea_"+
b+"_"+a).value=""):((g=this.getAnnotationData(d,a,b,g).annotationScoreValue)||(g=""),g!=f&&this.saveAnnotation(a,b,c,"score",f,d,e))}};
View.prototype.saveComment=function(a,b,c,d,e,f){this.resizeTextArea(f);if(e=="null")alert("You are trying to grade a work that has not yet been submitted.  We currently do not support this feature.");else{var f=document.getElementById("annotationCommentTextArea_"+b+"_"+a).value,g=this.getUserAndClassInfo().getAllTeacherWorkgroupIds();(g=this.getAnnotationData(d,a,b,g).annotationCommentValue)||(g="");g!=f&&this.saveAnnotation(a,b,c,"comment",f,d,e)}};
View.prototype.saveAnnotation=function(a,b,c,d,e,f,g){var h=this.getConfig().getConfigParam("postAnnotationsUrl"),e=encodeURIComponent(e);this.connectionManager.request("POST",1,h,{runId:f,nodeId:a,toWorkgroup:b,fromWorkgroup:c,annotationType:d,value:e,stepWorkId:g},function(a,b,c){var d=c[0],b=c[1],e=c[2],f=c[3],g=c[4],h=unescape(c[5]),m=c[6],c=c[7];isNaN(parseInt(a))?a=="ERROR:LoginRequired"?(alert("Your latest grade has not been saved.\n\nYou have been inactive for too long and have been logged out. Please log back in to continue."),
parent.window.location="/webapp/j_spring_security_logout"):(a=d.getUserAndClassInfo().getAllTeacherWorkgroupIds(),d.revertAnnotation(b,e,f,a,g,h,m,c)):(f=new Annotation(m,b,e,f,g,h,a,c),d.annotations.updateOrAddAnnotation(f),d=document.getElementById("studentWorkRow_"+e+"_"+b+"_"+c),d.className=d.className.replace("newWork",""),document.getElementById("lastAnnotationPostTime_"+e+"_"+b).innerHTML="Last Annotation: "+new Date(parseInt(a)))},[this,a,b,c,d,e,f,g],function(a,b){var c=b[0],d=b[1],e=b[2],
f=b[3],g=c.getUserAndClassInfo().getAllTeacherWorkgroupIds();c.revertAnnotation(d,e,f,g,b[4],b[5],b[6],b[7])})};View.prototype.revertAnnotation=function(a,b,c,d,e,f,g){alert("Failed to save "+e+", the "+e+" will be reverted back to its previous value.");c=this.annotations.getLatestAnnotation(g,a,b,d,e);d="";e=="score"?d="annotationScoreTextArea_":e=="comment"&&(d="annotationCommentTextArea_");c!=null?document.getElementById(d+b+"_"+a).value=c.value:document.getElementById(d+b+"_"+a).value=""};
View.prototype.saveFlag=function(a,b,c,d,e,f){if(f=="null")alert("You are trying to flag a work that has not yet been submitted.  We currently do not support this feature."),document.getElementById("flagButton"+b).checked=!1;else{deleteFlag=!document.getElementById("flagButton_"+f).checked;var e=this.getConfig().getConfigParam("postFlagsUrl"),g="",g=deleteFlag?"unflagged":"flagged";this.connectionManager.request("POST",1,e,{runId:d,nodeId:a,toWorkgroup:b,fromWorkgroup:c,stepWorkId:f,value:g,annotationType:"flag"},
function(e,j,i){j=i[0];e=new Annotation(d,a,b,c,"flag",g,e,f);j.annotations.updateOrAddAnnotation(e);deleteFlag?(document.getElementById("studentWorkRow_"+b+"_"+a+"_"+f).setAttribute("isflagged",!1),j.filterStudentRows()):document.getElementById("studentWorkRow_"+b+"_"+a+"_"+f).setAttribute("isflagged",!0)},[this,a,b,c,d,f],function(a,b){var c=b[0],d=b[1],e=b[2],f=c.getUserAndClassInfo().getAllTeacherWorkgroupIds(),g=b[5],c=c.flags.getLatestAnnotation(b[4],d,e,f,"flag");alert("Failed to save flag, the flag will be reverted back to its previous value.");
c?document.getElementById("flagButton_"+g).checked=!0:document.getElementById("flagButton_"+g).checked=!1})}};View.prototype.getAnnotations=function(){this.connectionManager.request("GET",1,this.getConfig().getConfigParam("getAnnotationsUrl"),null,function(a,b,c){b=c[0];b.annotations=Annotations.prototype.parseDataJSONString(a);eventManager.fire("getAnnotationsComplete");b.getFlags()},[this])};
View.prototype.getFlags=function(){this.connectionManager.request("GET",1,this.getConfig().getConfigParam("getFlagsUrl"),null,function(a,b,c){c[0].flags=Annotations.prototype.parseDataJSONString(a);eventManager.fire("getFlagsComplete")},[this])};View.prototype.checkAndSaveScore=function(a,b,c,d,e){this.saveScore(a,b,c,d,e)};
function removeFlaggedItemFromDisplay(a){var b=document.getElementById("flaggedItemsTable"),a=document.getElementById("flaggedItem"+a);b.childNodes[0].removeChild(a);flaggedItemsTableEmpty()&&addNoFlaggedResponsesMsg()}function addNoFlaggedResponsesMsg(){var a=document.getElementById("flaggedItemsTable"),b=document.createElement("tr");b.id="noFlaggedResponses";b.innerHTML="<td>No flagged responses</td>";flaggedItemsTableEmpty()&&a.childNodes[0].appendChild(b)}
function removeNoFlaggedResponsesMsg(){var a=document.getElementById("flaggedItemsTable"),b=document.getElementById("noFlaggedResponses");b!=null&&a.childNodes[0].removeChild(b)}function flaggedItemsTableEmpty(){return document.getElementById("flaggedItemsTable").childNodes[0].childNodes.length==1?document.getElementById("noFlaggedResponses")!=null?!0:!1:!1}
function showScores(){for(var a=vle.myClassInfo.classmates,b="score\tname\n",c=0;c<a.length;c++){var d=a[c],e=annotations.getTotalScoreByToWorkgroup(d.workgroupId);b+=e+"\t"+d.userName+"\n"}alert(b)}typeof eventManager!="undefined"&&eventManager.fire("scriptLoaded","vle/view/grading/gradingview_annotations.js");View.prototype.showColumns=function(){if(arguments.length>0){$(".gradeColumn").css("display","none");for(var a=0;a<arguments.length;a++)$("."+arguments[a]).css("display","")}else $(".gradeColumn").css("display","")};
View.prototype.onlyShowFilteredItemsOnClick=function(){if(document.getElementById("onlyShowFilteredItemsCheckBox")!=null)document.getElementById("onlyShowFilteredItemsCheckBox").checked?($("#studentWorkTable").filter("[isFlagged=false]").css("display","none"),this.gradingShowFlagged=!0):($("#studentWorkTable tr").css("display",""),this.gradingShowFlagged=!1)};
View.prototype.onlyShowWorkOnClick=function(){if(document.getElementById("onlyShowWorkCheckBox"))document.getElementById("onlyShowWorkCheckBox").checked?(this.showColumns("workColumn"),this.gradingHidePersonalInfo=!0):(this.showColumns(),this.gradingHidePersonalInfo=!1)};
View.prototype.initiateGradingDisplay=function(){removejscssfile("jquery-ui-1.8.7.custom.css","css");var a=window.location.search.match(/permission=(\w*)/);this.gradingPermission=a!=null&&a.length>1?window.location.search.match(/permission=(\w*)/)[1]:"read";this.gradingType=this.getConfig().getConfigParam("gradingType");this.originalStudentWorkRowOrder=[];this.studentWorkRowOrderObjects=[];this.studentWorkRowRevisions={};this.gradingType=="step"?(this.displayGradeByStepSelectPage(),eventManager.fire("initiateGradingDisplayStart")):
this.gradingType=="team"?(this.displayGradeByTeamSelectPage(),eventManager.fire("initiateGradingDisplayStart")):this.gradingType=="monitor"?(this.checkXMPPEnabled(),this.isXMPPEnabled&&(this.displayClassroomMonitorPage(),eventManager.fire("initiateClassroomMonitorDisplayStart"))):this.gradingType=="export"&&this.displayResearcherToolsPage();if(this.gradingType!="monitor"&&this.gradingType!="export"){this.getRevisions=!1;if(this.getConfig().getConfigParam("getRevisions")=="true")this.getRevisions=
!0;this.getPeerReviewWork();this.getStudentWork()}};
View.prototype.displayResearcherToolsPage=function(){var a="<div id='exportCenterButtons'>";a+="<table>";a+="<tr><td><input class='blueButton' type='button' value='"+this.getI18NString("grading_button_export_latest_student_work")+"' onClick=\"eventManager.fire('getLatestStudentWorkXLSExport')\"></input></td><td><input class='blueButton' type='button' value='"+this.getI18NString("grading_button_explanation")+"' onClick=\"eventManager.fire('displayExportExplanation', ['latestStudentWork'])\"></input></td><td>"+this.getI18NString("grading_button_export_latest_student_work_description")+
"</td></tr>";a+="<tr><td><input class='blueButton' type='button' value='"+this.getI18NString("grading_button_export_all_student_work")+"' onClick=\"eventManager.fire('getAllStudentWorkXLSExport')\"></input></td><td><input class='blueButton' type='button' value='"+this.getI18NString("grading_button_explanation")+"' onClick=\"eventManager.fire('displayExportExplanation', ['allStudentWork'])\"></input></td><td>"+this.getI18NString("grading_button_export_all_student_work_description")+"</td></tr>";a+=
"<tr><td><input class='blueButton' type='button' value='"+this.getI18NString("grading_button_export_idea_baskets")+"' onClick=\"eventManager.fire('getIdeaBasketsExcelExport')\"></input></td><td><input class='blueButton' type='button' value='"+this.getI18NString("grading_button_explanation")+"' onClick=\"eventManager.fire('displayExportExplanation', ['ideaBaskets'])\"></input></td><td>"+this.getI18NString("grading_button_export_idea_baskets_description")+"</td></tr>";a+="<tr><td><input class='blueButton' type='button' value='"+
this.getI18NString("grading_button_export_explanation_builder_work")+"' onClick=\"eventManager.fire('getExplanationBuilderWorkExcelExport')\"></input></td><td><input class='blueButton' type='button' value='"+this.getI18NString("grading_button_explanation")+"' onClick=\"eventManager.fire('displayExportExplanation', ['explanationBuilder'])\"></input></td><td>"+this.getI18NString("grading_button_export_explanation_builder_work_description")+"</td></tr>";a+="<tr><td><input class='blueButton' type='button' value='"+
this.getI18NString("grading_button_export_custom_work")+"' onClick=\"eventManager.fire('displayCustomExportPage')\"></input></td><td><input class='blueButton' type='button' value='"+this.getI18NString("grading_button_explanation")+"' onClick=\"eventManager.fire('displayExportExplanation', ['custom'])\"></input></td><td>"+this.getI18NString("grading_button_export_custom_work_description")+"</td></tr>";a+="<tr><td><input class='blueButton' type='button' value='"+this.getI18NString("grading_button_export_student_names")+
"' onClick=\"eventManager.fire('getStudentNamesExport')\"></input></td><td><input class='blueButton' type='button' value='"+this.getI18NString("grading_button_explanation")+"' onClick=\"eventManager.fire('displayExportExplanation', ['studentNames'])\"></input></td><td>"+this.getI18NString("grading_button_export_student_names_description")+"</td></tr>";a+="</table>";a+="</div>";$("#gradeWorkDiv").html(a);this.fixGradingDisplayHeight();eventManager.fire("getStudentWorkComplete")};
View.prototype.displayExportExplanation=function(a){var b="";b+="<input class='blueButton' type='button' value='Back To Researcher Tools' onClick=\"eventManager.fire('displayResearcherToolsPage');\"></input>";a=="latestStudentWork"?(b+="<h3>Export Latest Student Work</h3>",b+="<p>Export the latest work that each student has submitted. Each row represents the work for a workgroup. The columns represent which step the work is for.</p>",b+="<table class='exportExplanationTable'>",b+=this.getWorkgroupExportExplanations(),
b+=this.getRunExportExplanations(),b+=this.getLatestStudentWorkExportExplanations(),b+="</table>"):a=="allStudentWork"?(b+="<h3>Export All Student Work</h3>",b+="<p>Export all the work revisions the students have submitted. Each sheet represents a workgroup. The rows represent the student visiting a step along with the work they submitted for that step on that visit. The rows are ordered chronologically from oldest to newest so you can view how the student progressed through the project and if they ever went back to change their answer.</p>",
b+="<table class='exportExplanationTable'>",b+=this.getRunExportExplanations(),b+=this.getWorkgroupExportExplanations(),b+=this.getAllStudentWorkExportExplanations(),b+="</table>"):a=="ideaBaskets"?(b+="<h3>Export Idea Baskets</h3>",b+="<p>Export all the idea basket revisions. All of the revisions for all the workgroups are on a single sheet. The idea basket revisions are grouped together by 'Workgroup Id'. For each revision, there may be one or more ideas. Each idea receives its own row. As an example, if an idea basket revision contains 3 ideas, there will be 3 rows for that revision. You will also see that the 'Basket Revision' number is the same for those 3 rows. An idea basket revision is created anytime the idea basket is modified and then closed.</p>",
b+="<table class='exportExplanationTable'>",b+=this.getRunExportExplanations(),b+=this.getWorkgroupExportExplanations(),b+=this.getIdeaBasketsExportExplanations(),b+="</table>"):a=="explanationBuilder"?(b+="<h3>Export Explanation Builder Work</h3>",b+="<p>Export all the work revisions for explanation builder steps. Each sheet represents a workgroup. Each time a student submits work for an explanation builder step, the ideas that are used are grouped together by 'Step Work Id'. As an example, if a student used 3 ideas in an explanation builder step, there will be 3 rows with the same 'Step Work Id'.</p>",
b+="<table class='exportExplanationTable'>",b+=this.getWorkgroupExportExplanations(),b+=this.getRunExportExplanations(),b+=this.getExplanationBuilderWorkExportExplanations(),b+="</table>"):a=="custom"?(b+="<h3>Export Custom Student Work</h3>",b+="<p></p>",b+="<h4><i>Export Custom Latest Student Work</i></h4>",b+="<p>Export the latest work that each student has submitted for a custom set of steps that you choose. Each row represents the work for a workgroup. The columns represent which step the work is for.</p>",
b+="<table class='exportExplanationTable'>",b+=this.getWorkgroupExportExplanations(),b+=this.getRunExportExplanations(),b+=this.getLatestStudentWorkExportExplanations(),b+="</table>",b+="<br>",b+="<h4><i>Export Custom All Student Work</i></h4>",b+="<p>Export all the work revisions the students have submitted for a custom set of steps that you choose. Each sheet represents a workgroup. The rows represent the student visiting a step along with the work they submitted for that step on that visit. The rows are ordered chronologically from oldest to newest so you can view how the student progressed through the project and if they ever went back to change their answer.</p>",
b+="<table class='exportExplanationTable'>",b+=this.getWorkgroupExportExplanations(),b+=this.getRunExportExplanations(),b+=this.getAllStudentWorkExportExplanations(),b+="</table>"):a=="studentNames"&&(b+="<h3>Export Student Names</h3>",b+="<p>Export the student names along with their period, workgroup id, wise id, and login</p>",b+="<table class='exportExplanationTable'>",b+=this.getRunExportExplanations(),b+=this.getStudentNamesExportExplanations(),b+="</table>");b+="<br>";b+="<input class='blueButton' type='button' value='Back To Researcher Tools' onClick=\"eventManager.fire('displayResearcherToolsPage');\"></input>";
$("#gradeWorkDiv").html(b);this.fixGradingDisplayHeight()};
View.prototype.displayCustomExportPage=function(){var a="<h3>Custom Export Page</h3>";a+="<input class='blueButton' type='button' value='Back To Researcher Tools' onClick=\"eventManager.fire('displayResearcherToolsPage');\"></input>";a+="<input class='blueButton' type='button' value='Export Custom Latest Student Work' onClick=\"eventManager.fire('getCustomLatestStudentWorkExport')\"></input>";a+="<input class='blueButton' type='button' value='Export Custom All Student Work' onClick=\"eventManager.fire('getCustomAllStudentWorkExport')\"></input>";a+=
"<br>";a+="<input id='selectAllStepsCheckBox' type='checkbox' onClick=\"eventManager.fire('customSelectAllStepsCheckBoxClicked')\" /><p style='display:inline'>Select All Steps</p>";a+="<table>";this.activityNumber=0;a+=this.displayCustomExportPageHelper(this.getProject().getRootNode());a+="</table>";a+="<br>";a+="<input class='blueButton' type='button' value='Back To Researcher Tools' onClick=\"eventManager.fire('displayResearcherToolsPage');\"></input>";a+="<input class='blueButton' type='button' value='Export Custom Latest Student Work' onClick=\"eventManager.fire('getCustomLatestStudentWorkExport')\"></input>";
a+="<input class='blueButton' type='button' value='Export Custom All Student Work' onClick=\"eventManager.fire('getCustomAllStudentWorkExport')\"></input>";$("#gradeWorkDiv").html(a);this.fixGradingDisplayHeight()};
View.prototype.displayCustomExportPageHelper=function(a){var b="",c=a.id;if(a.isLeafNode()){var d=this.getProject().getVLEPositionById(c);b+="<tr><td class='chooseStepToGradeStepTd'><input id='stepCheckBox_"+c+"' class='activityStep_"+(this.activityNumber-1)+" activityCheckBox' type='checkbox' name='customExportStepCheckbox' value='"+c+"' style='margin-left:20px' /><p style='display:inline'>"+d+" "+a.getTitle()+" ("+a.type+")</p></td></tr>"}else{this.activityNumber!=0&&(b+="<tr><td class='chooseStepToGradeActivityTd'><input id='activityCheckBox_"+
this.activityNumber+"' class='stepCheckBox' type='checkbox' name='customExportActivityCheckbox' value='"+c+'\' onClick=\'eventManager.fire("customActivityCheckBoxClicked", ["activityCheckBox_'+this.activityNumber+"\"])' /><h4 style='display:inline'>Activity "+this.activityNumber+": "+a.getTitle()+"</h4></td></tr>");this.activityNumber++;for(c=0;c<a.children.length;c++)b+=this.displayCustomExportPageHelper(a.children[c])}return b};
View.prototype.customActivityCheckBoxClicked=function(a){var b=a.replace("activityCheckBox_",""),c=$("#"+a).attr("checked");$(".activityStep_"+b).each(function(a,b){$(b).attr("checked",c)})};View.prototype.customSelectAllStepsCheckBoxClicked=function(){var a=$("#selectAllStepsCheckBox").attr("checked");$(".stepCheckBox").each(function(b,c){$(c).attr("checked",a)});$(".activityCheckBox").each(function(b,c){$(c).attr("checked",a)})};
View.prototype.getGradingHeaderTableHtml=function(){var a="<div id='fixedGradingHeader' class='gradingHeader runButtons'>";a+="<div>";var b="",c="";this.gradingType=="step"?b="checked":this.gradingType=="team"&&(c="checked");a+="<a class='gradingButton "+b+"' onClick=\"eventManager.fire('displayGradeByStepSelectPage')\">"+this.getI18NString("grading_button_grade_by_step")+"</a>";a+="<a class='gradingButton "+c+"' onClick=\"eventManager.fire('displayGradeByTeamSelectPage')\">"+this.getI18NString("grading_button_grade_by_team")+
"</a>";a+="</div>";a+="<div style='float:right;'>";b=this.config.getConfigParam("runInfo");b!=null&&b!=""&&(b=JSON.parse(b),b.isStudentAssetUploaderEnabled!=null&&b.isStudentAssetUploaderEnabled&&(a+="<a onClick=\"eventManager.fire('displayStudentUploadedFiles')\">"+this.getI18NString("grading_button_view_student_uploaded_files")+"</a>"));a+="<a onClick=\"eventManager.fire('refreshGradingScreen')\">"+this.getI18NString("grading_button_check_for_new_student_work")+"</a>";a+="<a class='saveButton' onClick=\"notificationManager.notify('Changes have been successfully saved.')\">"+
this.getI18NString("grading_button_save_changes")+"</a>";a+="</div></div>";return a};
View.prototype.displayClassroomMonitorPage=function(){var a="<div id='classroomMonitorDiv>",b="<div id='pauseScreenDiv'>";b+="<h2 style='margin-bottom:0px'>Pause All Screens <span style='font-size:.8em'>(Currently all students' screens are: <span id='studentScreenStatus' style='font-weight:bold; color:green'>unpaused</span></span>)</h2>";b+="<div id='pauseScreenControls'>";b+="<table><tr>";b+="<td><div>This is what your students will see when you pause their screens:</div><textarea type='text' id='pause-message' rows='2' cols='90' value=''>Your teacher has paused your screen.</textarea></td>";b+=
"<td><input type='button' id='pause-button' value='pause' class='blueButton' style='background-color:red; margin: 20 0 20 20; font-size:1.5em'></input>";b+="<input type='button' id='unPause-button' value='un-pause' class='blueButton' style='background-color:green; margin: 20 0 20 20; font-size:1.5em'></input></td>";b+="</tr></table>";b+="</div></div>";a+=b;b="<div id='studentProgressDiv'>";b+="<h2>Student Progress</h2>";b+="</div>";a+=b;a+=this.createClassroomMonitorTable();a+="</div>";$("#gradeWorkDiv").html(a);
$("#teamStatusDialog").dialog({autoOpen:!1,width:400,height:300});this.applyTableSorterToClassroomMonitorTable();this.startXMPP();eventManager.fire("classroomMonitorDisplayComplete");this.displayFinished()};
View.prototype.createClassroomMonitorTable=function(){var a="";a+=this.getPeriodRadioButtonTableHtml("displayGradeByTeamSelectPage");a+="<table id='chooseTeamToGradeTable' class='chooseTeamToGradeTable tablesorter'>";a+="<thead><tr><th class='gradeColumn col1'>"+this.getI18NString("period")+"</th><th class='gradeColumn col2'>"+this.getI18NString("team")+"</th><th class='gradeColumn col3'>Current Step</th><th>"+this.getI18NString("grading_grade_by_team_percentage_project_completed")+"</th><th>Status</th></tr></thead>";
var b=this.getUserAndClassInfo().getClassmatesInAlphabeticalOrder();this.getMaxScoresSum(this.getProject().getNodeIds());this.getUserAndClassInfo().getAllTeacherWorkgroupIds();a+="<tbody>";for(var c=0;c<b.length;c++){var d=b[c],e=d.workgroupId,f=d.userName.replace(/:/g,"<br>"),d=d.periodName;a+="<tr id='classroomMonitorWorkgroupRow_"+e+"' class='"+("showScoreRow classroomMonitorStudentWorkRow studentWorkRow period"+d)+"' onClick=\"eventManager.fire('displayGradeByTeamGradingPage', ['"+e+"'])\">";
a+="<td class='showScorePeriodColumn'>"+d+"</td>";a+="<td class='showScoreWorkgroupIdColumn'>"+f+"</td>";a+="<td id='teamCurrentStep_"+e+"'>N/A</td>";a+="<td style='padding-left: 0pt;padding-right: 0pt' id='teamPercentProjectCompleted_"+e+"'>0%</td>";a+="<td id='teamStatus_"+e+"'></td></tr>"}a+="</tbody>";a+="</table>";a+="<div id='teamStatusDialog'></div>";return a};
View.prototype.applyTableSorterToClassroomMonitorTable=function(){$.tablesorter.addParser({id:"completion",is:function(){return!1},format:function(a){var b=a.indexOf("%");return a.substring(0,b)},type:"numeric"});$("#chooseTeamToGradeTable").tablesorter({headers:{3:{sorter:"completion"}}})};
View.prototype.displayGradeByTeamSelectPage=function(){this.gradingType="team";this.displayStart("displayGradeByTeamSelectPage");var a="";a+="<div class='gradingTools'>";a+=this.getGradingHeaderTableHtml();a+="<div id='periodSelect' class='gradingHeader'>"+this.getPeriodRadioButtonTableHtml("displayGradeByTeamSelectPage")+"</div>";a+="<div id='gradeTeamHeader' class='gradingHeader'><span class='instructions'>"+this.getI18NString("grading_grade_by_team_header")+"</span>";a+="<div style='float:right;'>Search for student: <input type='text' id='chooseTeamToGrade_search' /></div><div style='clear:both;'></div></div>";
a+="</div><div class='gradingContent'>";a+="<table id='chooseTeamToGradeTable' class='chooseTeamToGradeTable tablesorter'>";a+="<thead><tr><th class='gradeColumn col1'>"+this.getI18NString("period")+"</th><th class='gradeColumn col2'>"+this.getI18NString("team")+"</th><th class='gradeColumn col3'>"+this.getI18NString("grading_grade_by_team_teacher_graded_score")+"</th><th>"+this.getI18NString("grading_grade_by_step_items_to_review")+"</th><th>"+this.getI18NString("grading_grade_by_team_percentage_project_completed")+
"</th></tr></thead>";var b=this.getUserAndClassInfo().getClassmatesInAlphabeticalOrder(),c=this.getMaxScoresSum(this.getProject().getNodeIds()),d=this.getUserAndClassInfo().getAllTeacherWorkgroupIds();a+="<tbody>";for(var e=0;e<b.length;e++){var f=b[e],g=f.workgroupId,h=f.userName.replace(/:/g,"<br>"),f=f.periodName,j="showScoreRow studentWorkRow period"+f,i=this.annotations.getTotalScoreByToWorkgroupAndFromWorkgroups(g,d);a+="<tr class='"+j+"' onClick=\"eventManager.fire('displayGradeByTeamGradingPage', ['"+
g+"'])\"><td class='showScorePeriodColumn'>"+f+"</td><td class='showScoreWorkgroupIdColumn'><a>"+h+"</a></td><td class='showScoreScoreColumn'>"+i+" / "+c+"</td><td id='teamNumItemsNeedGrading_"+g+"'></td><td style='padding-left: 0pt;padding-right: 0pt' id='teamPercentProjectCompleted_"+g+"'></td></tr>"}a+="</tbody></table></div>";document.getElementById("gradeWorkDiv").innerHTML=a;this.calculateGradingStatistics("team");this.displayFinished()};
View.prototype.displayStudentUploadedFiles=function(){$("#studentAssetsDiv").size()==0&&($("#gradeWorkDiv").append('<div id="studentAssetsDiv" style="margin-bottom:.3em;"></div>'),$("#studentAssetsDiv").html("<div id='studentAssetEditorDialog' style='display: none;'><div class='hd'><div>Students' Files</div><div id='notificationDiv'></div><div id='allStudentsAssets' class='bd'></div></div><div class='bd'></div></div>"));$("#studentAssetsDiv").dialog({autoOpen:!1,closeText:"",resizable:!0,width:800,
height:600,position:[0,0],top:"20px",modal:!0,title:"Students' Uploaded Files",buttons:{Done:function(){$("#studentAssetsDiv").dialog("close")}}});var a=this.userAndClassInfo.getWorkgroupIdsInClass().join(":");this.connectionManager.request("POST",1,this.getConfig().getConfigParam("viewStudentAssetsUrl"),{forward:"assetmanager",workgroups:a,command:"assetList"},function(a,c,d){$("#allStudentsAssets").html("");$("#studentAssetsDiv").dialog("open");$("#studentAssetEditorDialog").show();for(var c=d.config.getConfigParam("getStudentUploadsBaseUrl"),
a=JSON.parse(a),e=0;e<a.length;e++){for(var f=a[e],g=f.assets.split("~"),f=f.workgroupId,h="<div><h3>"+d.userAndClassInfo.getUserNameByUserId(f)+"</h3><ul>",j=0;j<g.length;j++){var i=g[j];h+="<li><a target=_blank href='"+(c+"/"+f+"/"+i)+"'>"+i+"</a></li>"}h+="</ul></div>";$("#allStudentsAssets").append(h)}},this)};
View.prototype.displayGradeByStepSelectPage=function(){this.gradingType="step";this.displayStart("displayGradeByStepSelectPage");var a="",a="<div class='gradingTools'>";a+=this.getGradingHeaderTableHtml();a+="<div id='periodSelect' class='gradingHeader'>"+this.getPeriodRadioButtonTableHtml("displayGradeByStepSelectPage")+"</div>";a+="<div id='gradeStepHeader' class='gradingHeader'><table id='statisticsTable'><tr><td class='col1'><span style='font-weight: bold; font-size: 1.1em;'>"+this.getI18NString("grading_grade_by_step_header")+
"</span></td><td class='header col2'>"+this.getI18NString("grading_grade_by_step_point_value")+"</span></td><td class='header col3'>"+this.getI18NString("grading_grade_by_step_items_to_review")+"</td><td class='header col4'>"+this.getI18NString("grading_grade_by_step_average_class_score")+"</td><td class='header col5'>"+this.getI18NString("grading_grade_by_step_percent_completed_step")+"</td></tr></table></div>";a+="</div><div class='gradingContent'>";a+="<table id='chooseStepToGradeTable' class='chooseStepToGradeTable'><tbody>";
this.activityNumber=0;a+=this.displayGradeByStepSelectPageHelper(this.getProject().getRootNode());a+="</tbody></table>";a+="</div>";unlock();document.getElementById("gradeWorkDiv").innerHTML=a;this.calculateGradingStatistics("step");this.displayFinished()};
View.prototype.displayGradeByStepSelectPageHelper=function(a){var b="",c=a.id;if(a.isLeafNode())c=this.getProject().getVLEPositionById(c),b+=a.type=="HtmlNode"||a.type=="OutsideUrlNode"?this.getGradeByStepSelectPageLinklessHtmlForNode(a,c,a.type):a.type=="DuplicateNode"?this.getGradeByStepSelectPageHtmlForDuplicateNode(a,c):this.getGradeByStepSelectPageLinkedHtmlForNode(a,c,a.type);else{this.activityNumber!=0&&(b+="<tr><td class='chooseStepToGradeActivityTd'><h4>Activity "+this.activityNumber+": "+
a.getTitle()+"</h4></td><td class='header col2'></td><td class=' header col3'></td><td class='header col4'></td><td class='header col5'></td></tr>");this.activityNumber++;for(c=0;c<a.children.length;c++)b+=this.displayGradeByStepSelectPageHelper(a.children[c])}return b};View.prototype.getGradeByStepSelectPageLinklessHtmlForNode=function(a,b,c){return"<tr><td class='chooseStepToGradeStepTd' colspan='5'><p>Step: "+b+" "+a.getTitle()+" ("+c+")</p></td></tr>"};
View.prototype.getGradeByStepSelectPageHtmlForDuplicateNode=function(a,b){var c=a.getNode(),d=this.getProject().getVLEPositionById(c.id);return this.getGradeByStepSelectPageLinklessHtmlForNode(c,b,"Duplicate for "+c.type+" at "+d)};
View.prototype.getGradeByStepSelectPageLinkedHtmlForNode=function(a,b,c){var d=this.getMaxScoreValueByNodeId(a.id);statisticsForNode="<td class='statistic studentWorkRow col3 periodAll' id='stepNumItemsNeedGrading_"+a.id+"'></td><td class='statistic col4 studentWorkRow periodAll' id='stepAverageScore_"+a.id+"'></td><td style='padding-left: 0pt;padding-right: 0pt' class='statistic col5 studentWorkRow periodAll' id='stepPercentStudentsCompleted_"+a.id+"'></td>";for(var e=this.getUserAndClassInfo().getPeriodName().split(":"),
f=0;f<e.length;f++){var g=e[f];statisticsForNode+="<td class='statistic col3 studentWorkRow period"+g+"' id='stepNumItemsNeedGrading_"+a.id+"_period"+g+"' style='display:none'></td><td class='statistic col4 studentWorkRow period"+g+"' id='stepAverageScore_"+a.id+"_period"+g+"' style='display:none'></td><td class='statistic col5 studentWorkRow period"+g+"' id='stepPercentStudentsCompleted_"+a.id+"_period"+g+"' style='display:none'></td>"}e=this.isWriteAllowed();return"<tr><td class='chooseStepToGradeStepTd col1'>"+
('<a onClick=\'eventManager.fire("displayGradeByStepGradingPage",["'+b+'", "'+a.id+"\"])'>Step "+b+":&nbsp;&nbsp;"+a.getTitle()+"&nbsp;&nbsp;&nbsp;<span class='nodeTypeClass'>("+c+")</span></a>")+"</td><td class='chooseStepToGradeMaxScoreTd col2 statistic'><input id='maxScore_"+a.id+"' type='text' value='"+d+"' onblur='eventManager.fire(\"saveMaxScore\", ["+this.getConfig().getConfigParam("runId")+', "'+a.id+"\"])'"+e+"/></td>"+statisticsForNode+"</tr>"};
View.prototype.getTextAreaNumRows=function(a,b){for(var c=0,d=0,e=null,f=0,g=!1,h=0;h<b.length;h++){var j=b.charAt(h);if(j=="\n")c+=1,f=h,d=0,e=null;else if(j==" ")e=h,d+=1,d>=a&&(c+=1,f=h,d=0);else if(j!=" "&&(d+=1,d>=a)){var j=h+1,i=b.charAt(j);i==" "?(c+=1,f=j,d=0):i!="\n"&&(e==null||f==e?g=!0:(h=e,c+=1,d=0,f=h))}}g&&(c+=1);c+=1;return c};View.prototype.resizeTextArea=function(a){var b=a.cols,c=a.value;c==null&&(c="");a.rows=this.getTextAreaNumRows(b,c)};
View.prototype.displayGradeByStepGradingPage=function(a,b){if(!(b==null||b=="undefined")){this.displayStart("displayGradeByStepGradingPage",[a,b]);var c="",c="<div class='gradingTools'>";c+=this.getGradingHeaderTableHtml();c+="<div id='periodSelect' class='gradingHeader'>"+this.getPeriodRadioButtonTableHtml("displayGradeByStepGradingPage")+"</div>";c+="<div class='gradingHeader'><span class='instructions'>Current Step: "+a+" "+this.getProject().getNodeById(b).getTitle()+" <span class='nodeTypeClass'>("+
this.getProject().getNodeById(b).getType()+")</span></span>";c+="<div style='float:right;'>";var d=this.getProject().getPreviousAndNextNodeIds(b);c+="<a class='selectStep previousButtonClass' onClick='"+(d.previousNodeId?'eventManager.fire("displayGradeByStepGradingPage",["'+d.previousNodePosition+'", "'+d.previousNodeId+'"])':"return false;")+"'>"+this.getI18NString("grading_previous_step")+"</a>";c+="<a class='selectStep' onClick='eventManager.fire(\"displayGradeByStepSelectPage\")'>"+this.getI18NString("grading_change_step")+
"</a>";c+="<a class='selectStep nextButtonClass' onClick='"+(d.nextNodeId?'eventManager.fire("displayGradeByStepGradingPage",["'+d.nextNodePosition+'", "'+d.nextNodeId+'"])':"return false;")+"'>"+this.getI18NString("grading_next_step")+"</a>";c+="</div>";c+="<div id='filterOptions'>";d="";this.gradingHidePersonalInfo&&(d="checked");c+="<input type='checkbox' id='onlyShowWorkCheckBox' onClick=\"eventManager.fire('onlyShowWorkOnClick')\" "+d+"/><p>"+this.getI18NString("grading_hide_personal_info")+
"</p>";d="";this.gradingShowFlagged&&(d="checked");var e="";this.gradingShowSmartFiltered&&(e="checked");c+="<input type='checkbox' id='onlyShowFilteredItemsCheckBox' value='show filtered items' onClick=\"eventManager.fire('filterStudentRows')\" "+d+"/><p>"+this.getI18NString("grading_show_flagged_items_only")+"</p>";c+="<input type='checkbox' id='onlyShowSmartFilteredItemsCheckBox' value='show filtered items' onClick=\"eventManager.fire('filterStudentRows')\" "+e+"/><p id='onlyShowSmartFilteredItemsText'>"+
this.getI18NString("grading_show_smart_filtered_items_only")+"</p>";d="";this.gradingEnlargeStudentWorkText&&(d="checked");c+="<input type='checkbox' id='enlargeStudentWorkTextCheckBox' value='show filtered items' onClick=\"eventManager.fire('enlargeStudentWorkText')\" "+d+"/><p>"+this.getI18NString("grading_enlarge_student_work_text")+"</p>";d="";this.gradingShowRevisions&&(d="checked");this.getRevisions&&(c+="<input type='checkbox' id='showAllRevisions' value='show all revisions' onClick=\"eventManager.fire('filterStudentRows')\" "+
d+"/><p style='display:inline'>"+this.getI18NString("grading_show_all_revisions")+"</p>");this.project.getNodeById(b).getContent().getContentJSON().gradingCriteria!=null&&(d="",this.gradingSortByAutoGradedScore&&(d="checked"),c+="<input type='checkbox' id='sortByAutoGradedScoreCheckbox' value='sort by auto graded score checkbox' onClick=\"eventManager.fire('filterStudentRows')\" "+d+"/><p style='display:inline'>"+this.getI18NString("grading_sort_by_auto_graded_score_checkbox")+"</p>");c+="</div></div></div>";
c+="<div class='gradingContent'>";c+="<div class='questionContentContainer'><div class='questionContentHeader'><b>"+this.getI18NString("grading_question")+":</b><a onClick=\"eventManager.fire('togglePrompt', ['questionContentText_"+b+"'])\">"+this.getI18NString("grading_hide_show_question")+"</a>";c+="</div>";d=this.getProject().getNodePromptByNodeId(b);c+="<div id='questionContentText_"+b+"' class='questionContentText commentHidden'> "+d+"</div></div>";c+="<div id='flaggedItems'></div>";c+="<table id='studentWorkTable' class='studentWorkTable'>";
c+="<thead id='studentWorkTableHeaderRow'><th class='gradeColumn workgroupIdColumn'>"+this.getI18NString("team_caps")+"</th><th class='gradeColumn workColumn'>"+this.getI18NString("student_work")+"</th><th class='gradeColumn gradingColumn'>"+this.getI18NString("teacher_comment_and_score")+"</th><th class='gradeColumn annotationColumn'>"+this.getI18NString("tools")+"</th></thead>";for(var d=this.getVleStatesSortedByUserName(),e=this.getConfig().getConfigParam("runId"),f=this.getUserAndClassInfo().getWorkgroupId(),
g=this.getUserAndClassInfo().getAllTeacherWorkgroupIds(),h=this.getProject().getNodeById(b),b=h.id,j=0;j<d.length;j++){var i=d[j],l=i.dataId,o=this.getUserNamesByWorkgroupId(l,0),k=null,p=null,q=null,n=i.getNodeVisitsWithWorkByNodeId(b),m=null;n.length>0&&(m=n[n.length-1]);if(m!=null)k=m.id,p=m.getLatestWork(),q=m.visitPostTime;var p=this.getPeerOrTeacherReviewData(p,h,l,i),s=this.getAnnotationData(e,b,l,g),i=s.annotationCommentValue,r=s.annotationScoreValue,u=s.latestAnnotationPostTime,s=this.getUserAndClassInfo().getClassmatePeriodNameByWorkgroupId(l),
t=this.annotations.getLatestAnnotation(e,b,l,g,"flag"),w="",v="false";t&&t.value=="flagged"&&(w=" checked",v="true");t="studentWorkRow period"+s;m==null&&(t+=" noWork");u<q&&(t+=" newWork");m="studentWorkRow_"+l+"_"+b+"_"+k;this.originalStudentWorkRowOrder.push(m);c+="<tr class='"+t+"' id='"+m+"' isFlagged='"+v+"'>";v="";n.length>1?v="<a onClick=\"eventManager.fire('toggleGradingDisplayRevisions', ['"+l+"', '"+b+"'])\">"+(n.length-1)+" "+this.getI18NString("grading_hide_show_revisions")+"</a>":n.length==
1?v=this.getRevisions?this.getI18NString("grading_no_revisions"):this.getI18NString("grading_only_latest_revision_displayed"):n.length==0&&(v=this.getI18NString("grading_no_revisions"));c+="<td class='gradeColumn workgroupIdColumn'><div><a onClick=\"eventManager.fire('displayGradeByTeamGradingPage', ['"+l+"'])\">"+o+"</a></div><div>"+this.getI18NString("period")+" "+s+"</div><div>"+v+"</div></td>";t="";t=p==null?"disabled":this.isWriteAllowed();c+=this.getStudentWorkTdHtml(p,h,k,"gradeColumn workColumn",
q);c+=this.getScoringAndCommentingTdHtml(l,b,f,e,k,r,i,u,t,"gradeColumn gradingColumn",p,m);c+=this.getFlaggingTdHtml(l,b,f,e,k,t,w,"gradeColumn toolsColumn");c+="</tr>";if(n.length>1)for(k=n.length-2;k>=0;k--){var i=n[k],p=i.visitPostTime,q=i.getLatestWork(),x=i.id,u=this.getAnnotationDataForRevision(x),i=u.annotationCommentValue,r=u.annotationScoreValue,u=u.latestAnnotationPostTime,t="disabled",w="",v="false",y="studentWorkRow_"+l+"_"+b+"_"+x;this.originalStudentWorkRowOrder.push(y);c+="<tr id='"+
y+"' class='studentWorkRow period"+s+" studentWorkRevisionRow studentWorkRevisionRow_"+l+"_"+b+"' style='display:none' isFlagged='"+v+"'>";c+="<td class='gradeColumn workgroupIdColumn'><div>"+o+"</div><div>Revision "+(k+1)+"</div></td>";c+=this.getStudentWorkTdHtml(q,h,x,"gradeColumn workColumn",p);c+=this.getScoringAndCommentingTdHtml(l,b,f,e,x,r,i,u,t,"gradeColumn gradingColumn",q);c+=this.getFlaggingTdHtml(l,b,f,e,x,t,w,"gradeColumn toolsColumn");c+="</tr>";this.studentWorkRowRevisions[m]==null&&
(this.studentWorkRowRevisions[m]=[]);this.studentWorkRowRevisions[m].push(y)}}c+="</table></div></div>";document.getElementById("gradeWorkDiv").innerHTML=c;this.renderAllStudentWorkForNode(h);h.type=="MySystemNode"&&$(".mysystemCell").each(showDiagramNode);h.type=="SVGDrawNode"&&($(".svgdrawCell").each(showDrawNode),$(".snapCell").each(showSnaps));this.displayFinished()}};
View.prototype.calculateGradingStatistics=function(a){this.vleStates!=null&&(a==null&&(a=this.getConfig().getConfigParam("gradingType")),a=="step"?this.calculateGradeByStepGradingStatistics(this.getProject().getRootNode()):a=="team"&&this.calculateGradeByTeamGradingStatistics())};
View.prototype.calculateGradeByTeamGradingStatistics=function(){var a=this.getProject().getNodeIds(),b=this.getConfig().getConfigParam("runId");this.getUserAndClassInfo().getWorkgroupId();for(var c=this.getUserAndClassInfo().getAllTeacherWorkgroupIds(),d=0;d<this.vleStates.length;d++){for(var e=this.vleStates[d],f=e.dataId,g=0,h=0,j=0;j<a.length;j++){var i=a[j],l=e.getLatestNodeVisitByNodeId(i),o=null;if(l!=null)h++,o=l.visitPostTime;i=this.getAnnotationData(b,i,f,c).latestAnnotationPostTime;o>i&&
g++}h=Math.floor(h/a.length*100)+"%";e=parseInt(h.replace("%",""));h="<div class='pLabel'>"+h+"</div><div id='progress_"+f+"' class='progress'></div>";document.getElementById("teamNumItemsNeedGrading_"+f).innerHTML=g;document.getElementById("teamPercentProjectCompleted_"+f).innerHTML=h;f=document.getElementById("progress_"+f);$(f).progressbar({value:e})}var k=$("#chooseTeamToGradeTable").dataTable({aaSorting:[[1,"asc"]],iDisplayLength:-1,sDom:"<rt>"});$(".fixedHeader").detach();new FixedHeader(k);
$("input#chooseTeamToGrade_search").keypress(function(a){a.keyCode===13&&(a=$(this).val(),k.fnFilter(a))});this.displayFinished()};
View.prototype.calculateGradeByStepGradingStatistics=function(a){var b=a.id;if(a.isLeafNode()){if(!(a.type=="HtmlNode"||a.type=="OutsideUrlNode"||a.type=="DuplicateNode")){a=this.getGradeByStepGradingStatistics(b);document.getElementById("stepAverageScore_"+b).innerHTML=a.averageScore;document.getElementById("stepNumItemsNeedGrading_"+b).innerHTML=a.numItemsNeedScoring;var c=a.percentStudentsCompletedStep,d=parseInt(c.replace("%",""));document.getElementById("stepPercentStudentsCompleted_"+b).innerHTML=
"<div class='pLabel'>"+c+"</div><div id='progress_"+b+"' class='progress'></div>";c=document.getElementById("progress_"+b);$(c).progressbar({value:d});for(d=0;d<a.periods.length;d++){var e=a.periods[d],f=e.periodName,g=e.numItemsNeedGrading,c=e.percentStudentsCompletedStep,h=parseInt(c.replace("%","")),c="<div class='pLabel'>"+c+"</div><div id='progress_"+b+"_period"+f+"' class='progress'></div>",e=e.averageScore;document.getElementById("stepAverageScore_"+b+"_period"+f).innerHTML=e;document.getElementById("stepNumItemsNeedGrading_"+
b+"_period"+f).innerHTML=g;document.getElementById("stepPercentStudentsCompleted_"+b+"_period"+f).innerHTML=c;c=document.getElementById("progress_"+b+"_period"+f);$(c).progressbar({value:h})}}}else for(d=0;d<a.children.length;d++)this.calculateGradeByStepGradingStatistics(a.children[d])};
View.prototype.getGradeByStepGradingStatistics=function(a){var b={},c=0,d=this.getConfig().getConfigParam("runId");this.getUserAndClassInfo().getWorkgroupId();var e=this.getUserAndClassInfo().getAllTeacherWorkgroupIds(),f=0,g=0,h=0;this.getMaxScoreValueByNodeId(a);for(var j=0;j<this.vleStates.length;j++){var i=this.vleStates[j],l=i.dataId,o=this.getUserAndClassInfo().getClassmatePeriodNameByWorkgroupId(l),o=this.getPeriodGradingStatisticsObject(b,o),k=i.getLatestNodeVisitByNodeId(a),i=null;if(k!=
null)f++,o.numStudentsCompletedStep++,i=k.visitPostTime;k=this.getAnnotationData(d,a,l,e);l=k.annotationScoreValue;k=k.latestAnnotationPostTime;l!=null&&l!=""&&(g+=parseFloat(l),o.sumOfScoredValues+=parseFloat(l),h++,o.numOfScoredValues++);i>k&&(c++,o.numItemsNeedGrading++);o.numStudentsInPeriod++}a=Math.floor(f/this.vleStates.length*100)+"%";g/=h;isNaN(g)?g="N/A":(h=g.toString(),d=h.indexOf("."),d!=-1&&h.substring(d+1).length>1&&(g=g.toFixed(1)));b.numItemsNeedScoring=c;b.percentStudentsCompletedStep=
a;b.averageScore=g;this.calculatePeriodGradingStatistics(b);return b};View.prototype.getPeriodGradingStatisticsObject=function(a,b){if(a.periods==null)a.periods=[];for(var c=null,d=0;d<a.periods.length;d++){var e=a.periods[d];if(e.periodName==b){c=e;break}}if(c==null)c={},c.periodName=b,c.numItemsNeedGrading=0,c.numStudentsCompletedStep=0,c.sumOfScoredValues=0,c.numOfScoredValues=0,c.numStudentsInPeriod=0,a.periods.push(c);return c};
View.prototype.calculatePeriodGradingStatistics=function(a){if(a.periods==null)a.periods=[];for(var b=0;b<a.periods.length;b++){var c=a.periods[b],d=c.numItemsNeedGrading,e=Math.floor(c.numStudentsCompletedStep/c.numStudentsInPeriod*100)+"%",f=c.sumOfScoredValues/c.numOfScoredValues;if(isNaN(f))f="N/A";else{var g=f.toString(),h=g.indexOf(".");h!=-1&&g.substring(h+1).length>1&&(f=f.toFixed(1))}c.numItemsNeedScoring=d;c.percentStudentsCompletedStep=e;c.averageScore=f}};
View.prototype.getAnnotationData=function(a,b,c,d){return this.getAnnotationDataHelper(a,b,c,d,null)};View.prototype.getAnnotationDataForRevision=function(a){return this.getAnnotationDataHelper(null,null,null,null,a)};
View.prototype.getAnnotationDataHelper=function(a,b,c,d,e){var f={},g=null,h=null;e==null?(g=this.annotations.getLatestAnnotation(a,b,c,d,"comment"),h=this.annotations.getLatestAnnotation(a,b,c,d,"score")):(g=this.annotations.getAnnotationByStepWorkIdType(e,"comment"),h=this.annotations.getAnnotationByStepWorkIdType(e,"score"));f.annotationCommentValue="";f.annotationCommentPostTime="";if(g!=null)f.annotationCommentValue=g.value,f.annotationCommentPostTime=g.postTime;f.annotationScoreValue="";f.annotationScorePostTime=
"";if(h!=null)f.annotationScoreValue=h.value,f.annotationScorePostTime=h.postTime;f.latestAnnotationPostTime=Math.max(f.annotationCommentPostTime,f.annotationScorePostTime);return f};
View.prototype.getStudentWorkTdHtml=function(a,b,c,d,e){var f="";if(a==null)a="<div style='text-align:center'>"+this.getI18NString("grading_no_work_warning")+"</div>";else if(a!=""&&b.type=="MySystemNode"){var g="mysystemDiagram_"+c+"_"+e,h=this.config.getConfigParam("getContentBaseUrl"),j=b.getContent().getContentString(),j=j.replace(/\.\/images\//gmi,"images/"),j=j.replace(/images\//gmi,h+"/images/"),j=j.replace(/\.\/assets\//gmi,"assets/"),j=j.replace(/assets\//gmi,h+"/assets/"),i=a.replace(/\.\/images\//gmi,
"images/"),i=i.replace(/images\//gmi,h+"/images/"),i=i.replace(/\.\/assets\//gmi,"assets/"),i=i.replace(/assets\//gmi,h+"/assets/"),l=b.getContent().getContentUrl(),a="<a class='msEnlarge' style='text-decoration:underline; color:blue;' onclick='enlargeMS(\""+g+"\");'>enlarge</a><span id='content_"+g+"' style='display:none'>"+j+"</span><span id='contenturl_"+g+"' style='display:none'>"+l+"</span><span id='studentwork_"+g+"' style='display:none'>"+i+"</span><div id='"+g+"' contentBaseUrl='"+h+"' class='mysystemCell'  style=\"height:350px;\">"+
a+"</div>";a+="<br><br><br><p class='lastAnnotationPostTime'>"+this.getI18NString("timestamp")+": "+new Date(e)+"</p>"}else if(a!=""&&b.type=="SVGDrawNode"){g="svgDraw_"+c+"_"+e;h=this.config.getConfigParam("getContentBaseUrl");typeof a=="string"&&a.match(/^--lz77--/)&&(l=new LZ77,a=a.replace(/^--lz77--/,""),a=l.decompress(a),a=$.parseJSON(a));var i=a.svgString,o=a.description,j=a.snapshots,l=b.getContent().getContentUrl(),a="<div id='"+g+"_contentUrl' style='display:none;'>"+l+"</div><a class='drawEnlarge' onclick='enlargeDraw(\""+
g+"\");'>enlarge</a>";i!=null&&(i.match(/^--lz77--/)&&(l=new LZ77,i=i.replace(/^--lz77--/,""),i=l.decompress(i)),i=i.replace(/(<image.*xlink:href=)"(.*)"(.*\/>)/gmi,function(a,b,c){return c.indexOf("http://")==-1?a.replace(/(<image.*xlink:href=)"(.*)"(.*\/>)/gmi,'$1"'+h+'$2"$3'):a}),i=i.replace(/(marker.*=)"(url\()(.*)(#se_arrow_bk)(\)")/gmi,'$1"$2$4$5'),i=i.replace(/(marker.*=)"(url\()(.*)(#se_arrow_fw)(\)")/gmi,'$1"$2$4$5'),i=i.replace(/<g>/gmi,'<g transform="scale(0.6)">'),i=Utils.encode64(i));
if(j.length>0){b="<div id='"+g+"_snaps' class='snaps'>";for(i=0;i<j.length;i++){var o=g+"_snap_"+i,k=j[i].svg;k.match(/^--lz77--/)&&(l=new LZ77,k=k.replace(/^--lz77--/,""),k=l.decompress(k));k=k.replace(/(<image.*xlink:href=)"(.*)"(.*\/>)/gmi,function(a,b,c){return c.indexOf("http://")==-1?a.replace(/(<image.*xlink:href=)"(.*)"(.*\/>)/gmi,'$1"'+h+'$2"$3'):a});k=k.replace(/(marker.*=)"(url\()(.*)(#se_arrow_bk)(\)")/gmi,'$1"$2$4$5');k=k.replace(/(marker.*=)"(url\()(.*)(#se_arrow_fw)(\)")/gmi,'$1"$2$4$5');
k=k.replace(/<g>/gmi,'<g transform="scale(0.2)">');k=Utils.encode64(k);b+="<div id="+o+" class='snapCell' onclick='enlargeDraw(\""+g+"\");'>"+k+"</div>";b+="<div id='"+o+"_description' class='snapDescription' style='display:none;'>"+j[i].description+"</div>"}b+="</div>";a+=b}else a+="<div id='"+g+"' class='svgdrawCell'>"+i+"</div>",o!=null&&(a+="<span>Description: </span><div id='"+g+"_description' class='drawDescription'>"+o+"</div>");a+="<div class='lastAnnotationPostTime'>"+this.getI18NString("timestamp")+
": "+new Date(e)+"</div>"}else a!=""&&this.isSelfRenderingGradingViewNodeType(b.type)?a='<div id="studentWorkDiv_'+c+'" style="overflow:auto;width:500px"></div>':(a+="<div class='lastAnnotationPostTime'>"+this.getI18NString("timestamp")+": "+new Date(e)+"</div>",a=this.replaceSlashNWithDiv(a),a='<div id="studentWorkDiv_'+c+'" class="studentWorkDiv" style="overflow:auto; width:500px">'+a+"</div>");f+="<td id='studentWorkColumn_"+c+"' class='"+d+"'>"+a+"</td>";return f};
View.prototype.getPeerOrTeacherReviewData=function(a,b,c,d){if(a==null)return a;var e=b.content.getContentJSON();if(b!=null&&b.peerReview!=null)if(b.peerReview=="annotate"){var d=b.associatedStartNode,f=this.getPeerReviewWorkByReviewerNodeId(c,d);if(f!=null)d=f.stepWork,c="N/A",b=f.workgroupId,b!=null&&(b==-2?c="Canned Response":(c=this.getUserNamesByWorkgroupId(b,1),c="<a onClick=\"eventManager.fire('displayGradeByTeamGradingPage', ['"+b+"'])\">"+c+"</a>")),f="",d==null&&b==-2?f=e.authoredWork:d!=
null&&(d=NODE_VISIT.prototype.parseDataJSONObj(d,this),d!=null&&(f=d.getLatestWork())),a="<u>Other student:</u><br>"+c+"<br><br><u>Work written by other student:</u><br>"+f+"<br><br><u>Review written by this student:</u><br>"+a}else{if(b.peerReview=="revise"&&(d=b.associatedStartNode,f=this.getPeerReviewWorkByWorkerNodeId(c,d),f!=null&&(d=f.stepWork,d!=null&&(d=NODE_VISIT.prototype.parseDataJSONObj(d,this),d!=null)))){d=d.getLatestWork();b=f.annotation;f=f.reviewerWorkgroupId;c="N/A";f!=null&&(f==
-2?c="Canned Response":(c=this.getUserNamesByWorkgroupId(f,1),c="<a onClick=\"eventManager.fire('displayGradeByTeamGradingPage', ['"+f+"'])\">"+c+"</a>"));var g="";if(b!=null)g=b.value;else if(b==null&&f==-2)g=e.authoredReview;a="<u>Original work written by this student:</u><br>"+d+"<br><br><u>Other student:</u><br>"+c+"<br><br><u>Review written by other student:</u><br>"+g+"<br><br><u>Revised work written by this student:</u><br>"+a}}else if(b!=null&&b.teacherReview!=null)if(b.teacherReview=="annotate")a=
"<u>Work written by teacher:</u><br>"+e.authoredWork+"<br><br><u>Review written by this student:</u><br>"+a;else if(b.teacherReview=="revise"){e=b.associatedStartNode;d=d.getLatestNodeVisitByNodeId(e).getLatestWork();b="";if(this.annotations!=null&&(e=this.annotations.getLatestAnnotation(this.getConfig().getConfigParam("runId"),e,c,this.getUserAndClassInfo().getAllTeacherWorkgroupIds(),"comment"),e!=null))b=e.value;a="<u>Original work written by this student:</u><br>"+d+"<br><br><u>Review written by teacher:</u><br>"+
b+"<br><br><u>Revised work written by this student:</u><br>"+a}return a};
View.prototype.getScoringAndCommentingTdHtml=function(a,b,c,d,e,f,g,h,j,i,l,o){var k="",p=this.getMaxScoreValueByNodeId(b),q=this.getTextAreaNumRows(40,g),n=new Date(h),h="",h=n!=null&&n.getTime()!=(new Date(0)).getTime()?""+this.getI18NString("last_annotation")+": "+n:""+this.getI18NString("last_annotation")+": "+this.getI18NString("not_available")+"";k+="<td class='"+i+"'>";i=this.project.getNodeById(b).getContent().getContentJSON();if(i.gradingCriteria!=null){var i=i.gradingCriteria,m=n=0;k+="<table id='teacherGradingCriteriaTable' class='gradingCriteriaTable'>";
k+="<tr>";k+="<td class='gradingCriteriaTd'>Criteria</td>";k+="<td class='gradingCriteriaTd'>Auto Score</td>";k+="<td class='gradingCriteriaTd'>Possible Score</td>";k+="</tr>";for(var s=0;s<i.length;s++){var r=i[s],u=r.name,t=r.pointValue,w=0;this.runGradingCriteria(l,r)&&(w=t);m+=t;n+=w;k+="<tr>";k+="<td class='gradingCriteriaTd'>"+u+"</td>";k+="<td class='gradingCriteriaTd'>"+w+"</td>";k+="<td class='gradingCriteriaTd'>"+t+"</td>";k+="</tr>"}k+="<tr>";k+="<td class='gradingCriteriaTd'>Total</td>";
k+="<td class='gradingCriteriaTd'>"+n+"</td>";k+="<td class='gradingCriteriaTd'>"+m+"</td>";k+="</tr>";o!=null&&this.studentWorkRowOrderObjects.push({studentWorkRowId:o,autoGradedScore:n});k+="</table>"}k+="<table class='teacherAnnotationTable'>";k+="<tr><td>"+this.getI18NString("score")+": <input type='text' id='annotationScoreTextArea_"+a+"_"+b+"' value='"+f+"' onblur=\"eventManager.fire('saveScore', ['"+b+"','"+a+"', '"+c+"', '"+d+"', '"+e+"'])\" "+j+"/> / "+p+"</td></tr>";f="";j!="disabled"&&
(f='<a onclick=\'eventManager.fire("openPremadeComments", ["annotationCommentTextArea_'+a+"_"+b+'", "studentWorkColumn_'+e+"\"])'>"+this.getI18NString("grading_open_premade_comments")+"</a>");k+="<tr><td>"+this.getI18NString("comment")+": "+f+"<br><textarea wrap='soft' cols='40' rows='"+q+"' id='annotationCommentTextArea_"+a+"_"+b+"' onblur=\"eventManager.fire('saveComment', ['"+b+"','"+a+"', '"+c+"', '"+d+"', '"+e+"', this])\""+j+">"+g+"</textarea></td></tr>";k+="<tr><td><p id='lastAnnotationPostTime_"+
a+"_"+b+"' class='lastAnnotationPostTime'>"+h+"</p></td></tr>";k+="</table>";k+="</td>";return k};View.prototype.runGradingCriteria=function(a,b){var c=!1;a==null&&(a="");var d=b.values,e=b.operator;e=="and"?c=!0:e=="or"&&(c=!1);d.length==0&&(c=!0);for(var f=0;f<d.length;f++){var g=d[f];typeof g=="string"?c=a.indexOf(g)==-1?this.evaluateConditional(e,c,!1):this.evaluateConditional(e,c,!0):typeof g=="object"&&(g=this.runGradingCriteria(a,g),c=this.evaluateConditional(e,c,g))}return c};
View.prototype.evaluateConditional=function(a,b,c){var d=!1;a=="or"?d=b||c:a=="and"&&(d=b&&c);return d};View.prototype.getFlaggingTdHtml=function(a,b,c,d,e,f,g,h){return"<td class='"+h+"'><div></div><div class='gradeColumn flagColumn'><input type='checkbox' value='Flag' name='flagButton"+a+"' id='flagButton_"+e+'\' onClick=\'eventManager.fire("saveFlag", ["'+b+'", '+a+", "+c+", "+d+', null, "'+e+"\"])' "+f+" "+g+">"+this.getI18NString("flag")+"</div></td>"};
View.prototype.displayGradeByTeamGradingPage=function(a){$(".fixedHeader").detach();this.displayStart("displayGradeByTeamGradingPage",[a]);var b="",b="<div class='gradingTools'>";b+=this.getGradingHeaderTableHtml();var c=this.getUserNamesByWorkgroupId(a,0);b+="<div class='gradingHeader'><span class='instructions'>Current Team: "+c+"</span>";b+="<div style='float:right;'>";b+="<a class='selectStep' onClick='eventManager.fire(\"displayGradeByTeamSelectPage\")'>"+this.getI18NString("grading_change_team")+
"</a>";b+="</div>";b+="<div id='filterOptions'>";c="";this.gradingShowRevisions&&(c="checked");this.getRevisions&&(b+="<div><input type='checkbox' id='showAllRevisions' value='show all revisions' onClick=\"eventManager.fire('filterStudentRows')\" "+c+"/><p style='display:inline'>"+this.getI18NString("grading_show_all_revisions")+"</p></div>");b+="</div></div></div>";b+="<div class='gradingContent'>";c=this.getVleStateByWorkgroupId(a);this.activityNumber=0;b+=this.displayGradeByTeamGradingPageHelper(this.getProject().getRootNode(),
c);b+="</div>";document.getElementById("gradeWorkDiv").innerHTML=b;this.renderAllStudentWorkForWorkgroupId(a);$(".mysystemCell").each(showDiagramNode);$(".svgdrawCell").each(showDrawNode);$(".snapCell").each(showSnaps);this.displayFinished()};
View.prototype.displayGradeByTeamGradingPageHelper=function(a,b){var c=a.id,d="";if(a.isLeafNode()){var e=this.getProject().getVLEPositionById(c);if(a.type=="HtmlNode"||a.type=="OutsideUrlNode")d+="<table class='gradeByTeamGradingPageNonWorkStepTable'><tr><td class='chooseStepToGradeStepTd'><p>"+e+" "+a.getTitle()+" ("+a.type+")</p></td></tr></table>",d+="<br>";else if(a.type=="DuplicateNode"){var c=a.getNode(),f=this.getProject().getVLEPositionById(c.id),c="Duplicate for "+c.type+" at "+f;d+="<table class='gradeByTeamGradingPageNonWorkStepTable'><tr><td class='chooseStepToGradeStepTd'><p>"+
e+" "+a.getTitle()+" ("+c+")</p></td></tr></table>"}else{var f=this.getConfig().getConfigParam("runId"),g=this.getUserAndClassInfo().getWorkgroupId(),h=this.getUserAndClassInfo().getAllTeacherWorkgroupIds(),j=b.dataId,i=this.getAnnotationData(f,c,j,h),l=i.annotationCommentValue,o=i.annotationScoreValue,k=i.latestAnnotationPostTime,i=this.getUserAndClassInfo().getClassmatePeriodNameByWorkgroupId(j),p=b.getNodeVisitsWithWorkByNodeId(c),q=null;p.length>0&&(q=p[p.length-1]);var n=null,m=null,s=null;if(q!=
null)n=q.id,m=q.getLatestWork(),s=q.visitPostTime;var r=this.annotations.getLatestAnnotation(f,c,j,h,"flag"),h="",q="false";r&&r.value=="flagged"&&(h=" checked",q="true");m=this.getPeerOrTeacherReviewData(m,a,j,b);r="gradeByTeamGradingPageWorkStepTable";k<s&&(r+=" newWork");var u="";p.length>1?u="  <a onClick=\"eventManager.fire('toggleGradingDisplayRevisions', ['"+j+"', '"+c+"'])\">"+(p.length-1)+" "+this.getI18NString("grading_hide_show_revisions")+"</a>":p.length==1?u=this.getRevisions?this.getI18NString("grading_no_revisions"):
this.getI18NString("grading_only_latest_revision_displayed"):p.length==0&&(u=this.getI18NString("grading_no_revisions"));d+="<table id='studentWorkRow_"+j+"_"+c+"_"+n+"' class='"+r+"'>";d+="<thead class='gradeTeamTableHeader'><tr><td>"+this.getI18NString("student_work")+"</td><td>"+this.getI18NString("teacher_comment_and_score")+"</td><td>"+this.getI18NString("tools")+"</td></tr></thead>";d+="<tr><td class='chooseStepToGradeStepTd'><a onClick='eventManager.fire(\"displayGradeByStepGradingPage\",[\""+
e+'", "'+c+"\"])'>"+e+" "+a.getTitle()+"</a>&nbsp;&nbsp;<span class='byTeamStepType'>("+a.type+")</span></td>";d+="<td class='chooseStepToGradeStepTd2 colspan='2'><a onClick=\"eventManager.fire('togglePrompt', ['questionContentText_"+c+"'])\">"+this.getI18NString("grading_hide_show_question")+"</a>"+u+"</td>";d+="</tr>";e=this.getProject().getNodePromptByNodeId(c);d+="<tr>";d+="<td></td><td colspan='2'><div id='questionContentText_"+c+"' class='questionContentText commentHidden'> "+e+"</div></td>";
d+="</tr>";d+="<tr class='studentWorkRow period"+i+"' isFlagged='"+q+"'>";d+=this.getStudentWorkTdHtml(m,a,n,"gradeByTeamWorkColumn",s);e="";e=m==null?"disabled":this.isWriteAllowed();d+=this.getScoringAndCommentingTdHtml(j,c,g,f,n,o,l,k,e,"gradeByTeamGradeColumn gradeColumn gradingColumn",m);d+=this.getFlaggingTdHtml(j,c,g,f,n,e,h,"gradeByTeamToolsColumn gradeColumn toolsColumn");d+="</tr>";if(p.length>1)for(n=p.length-2;n>=0;n--)m=p[n],s=m.visitPostTime,q=m.getLatestWork(),r=m.id,k=this.getAnnotationDataForRevision(r),
l=k.annotationCommentValue,o=k.annotationScoreValue,k=k.latestAnnotationPostTime,e="disabled",h="",d+="<tr id='studentWorkRow_"+j+"_"+c+"_"+r+"' class='studentWorkRow period"+i+" studentWorkRevisionRow studentWorkRevisionRow_"+j+"_"+c+"' style='display:none'>",d+=this.getStudentWorkTdHtml(q,a,r,"gradeByTeamWorkColumn",s),d+=this.getScoringAndCommentingTdHtml(j,c,g,f,m.id,o,l,k,e,"gradeByTeamGradeColumn gradeColumn gradingColumn",q),d+=this.getFlaggingTdHtml(j,c,g,f,r,e,h,"gradeByTeamToolsColumn gradeColumn toolsColumn"),
d+="</tr>";d+="</table>";d+="<br>"}}else{this.activityNumber!=0&&(d+="<table class='gradeByTeamGradingPageActivityTable'><tr><td colspan='2' class='chooseStepToGradeActivityTd'><h4>Activity "+this.activityNumber+": "+a.getTitle()+"</h4></td><td></td></tr></table>",d+="");this.activityNumber++;for(c=0;c<a.children.length;c++)d+=this.displayGradeByTeamGradingPageHelper(a.children[c],b)}return d};
View.prototype.getVleStatesSortedByUserName=function(){var a=this.vleStates,b=this;return a=a.sort(function(a,d){var e=b.getUserAndClassInfo().getClassmateByWorkgroupId(a.dataId).userName.toLowerCase(),f=b.getUserAndClassInfo().getClassmateByWorkgroupId(d.dataId).userName.toLowerCase();return e>f})};
View.prototype.getUserNamesByWorkgroupId=function(a,b){b==null&&(b=1);var c="";if(a!=null){var d=this.getUserAndClassInfo().getClassmateByWorkgroupId(a);if(d!=null)for(var d=d.userName.split(":"),e=0;e<d.length;e++){if(c!=""){b==0&&(c+=", ");for(var f=0;f<b;f++)c+="<br />"}c+=d[e]}}return c};
View.prototype.getPeriodRadioButtonTableHtml=function(){var a="";a+="<div id='choosePeriod'>";var b=this.getUserAndClassInfo().getPeriodName().split(":"),c="";if(!this.gradingPeriod||this.gradingPeriod=="all")c="checked",this.gradingPeriod="all";a+="<span style='margin-right:.5em';>View:</span><a id='all' class='periodChoice "+c+"' onClick=\"eventManager.fire('setSelectedPeriod',this)\">"+this.getI18NString("grading_grade_by_step_all_periods")+"</a>";for(c=0;c<b.length;c++){var d="";this.gradingPeriod&&
this.gradingPeriod.replace("period","")==b[c]&&(d="checked");a+="<a id='period"+b[c]+"' class='periodChoice "+d+"' onClick=\"eventManager.fire('setSelectedPeriod',this)\">Period "+b[c]+"</a>"}a+="</div>";return a};View.prototype.setDisplayVisibleIfNotRevision=function(a){a.style.display=a.className.indexOf("studentWorkRevisionRow")==-1?"":"none"};
View.prototype.togglePrompt=function(a){a=document.getElementById(a);if(a!=null){var b=a.className;if(b!=null)if(b.indexOf("commentShown")!=-1)a.className=a.className.replace("commentShown","commentHidden");else if(b.indexOf("commentHidden")!=-1)a.className=a.className.replace("commentHidden","commentShown")}};View.prototype.refreshGradingScreen=function(){this.reloadGradingDisplay=this.currentGradingDisplay;this.reloadGradingDisplayParam=this.currentGradingDisplayParam;this.getAnnotations()};
View.prototype.reloadRefreshScreen=function(){this.reloadGradingDisplay!=null&&eventManager.fire(this.reloadGradingDisplay,this.reloadGradingDisplayParam);this.reloadGradingDisplayParam=this.reloadGradingDisplay=null};View.prototype.displayStart=function(a,b){this.currentGradingDisplay=a;this.currentGradingDisplayParam=b;$(window).resize(function(){this.fixGradingDisplayHeight()})};
View.prototype.displayFinished=function(){this.gradingType!="team"&&$(".fixedHeader").detach();parent.scrollTo(0,0);this.filterStudentRows();this.fixGradingDisplayHeight()};
View.prototype.fixGradingDisplayHeight=function(){var a=$("#gradingIfrm",window.parent.parent.document).height();$("#topifrm",parent.document).height(a);a-=$(".gradingTools").outerHeight();$(".gradingContent").height(a-14);this.gradingType=="step"?$("#statisticsTable").width($("#chooseStepToGradeTable").width()+1):this.gradingType=="team"&&$(".fixedHeader").width($("#chooseTeamToGradeTable_wrapper").width())};
View.prototype.toggleGradingDisplayRevisions=function(a,b){for(var c=this.getElementsByClassName(null,"studentWorkRevisionRow_"+a+"_"+b,null),d=0;d<c.length;d++){var e=c[d];if(e.style.display=="none"){if(e.style.display="",e.id.indexOf("studentWorkRow")!=-1){var f=this.getStudentWorkIdFromStudentWorkRowId(e.id),a=this.getWorkgroupIdFromStudentWorkRowId(e.id);this.renderStudentWork(f,a)}}else e.style.display="none"}this.fixGradingDisplayHeight()};
View.prototype.getPeriodFilterSelected=function(){var a=null;$(".periodChoice").each(function(){$(this).hasClass("checked")&&(a=$(this).attr("id"))});a&&(a=a.replace("period",""));return a};View.prototype.isFlaggedItemsChecked=function(){var a=null,b=document.getElementById("onlyShowFilteredItemsCheckBox");if(b)a=b.checked;return a};View.prototype.isSmartFilterChecked=function(){var a=null,b=document.getElementById("onlyShowSmartFilteredItemsCheckBox");if(b)a=b.checked;return a};
View.prototype.isShowRevisions=function(){var a=null,b=document.getElementById("showAllRevisions");if(b)a=b.checked;return a};View.prototype.isHidePersonalInfo=function(){var a=null,b=document.getElementById("onlyShowWorkCheckBox");if(b)a=b.checked;return a};View.prototype.isEnlargeStudentWorkText=function(){var a=null,b=document.getElementById("enlargeStudentWorkTextCheckBox");if(b)a=b.checked;return a};
View.prototype.isSortByAutoGradedScoreChecked=function(){var a=!1;$("#sortByAutoGradedScoreCheckbox").length!=0&&$("#sortByAutoGradedScoreCheckbox").attr("checked")=="checked"&&(a=!0);return a};View.prototype.setSelectedPeriod=function(a){$(".periodChoice").removeClass("checked");$(a).addClass("checked");this.filterStudentRows()};
View.prototype.filterStudentRows=function(){var a=this.getPeriodFilterSelected();if(a!=null)this.gradingPeriod=a;var b=this.isFlaggedItemsChecked();if(b!=null)this.gradingShowFlagged=b;var c=this.isSmartFilterChecked();if(c!=null)this.gradingShowSmartFiltered=c;var d=this.isShowRevisions();if(d!=null)this.gradingShowRevisions=d;var e=this.isHidePersonalInfo();if(e!=null)this.gradingHidePersonalInfo=e;e=this.isEnlargeStudentWorkText();if(e!=null)this.gradingEnlargeStudentWorkText=e;this.currentGradingDisplayParam&&
this.currentGradingDisplay=="displayGradeByStepGradingPage"&&(e=this.currentGradingDisplayParam[1],this.getProject().getNodeById(e).showSmartFilter(c));for(var e=this.getElementsByClassName(null,"studentWorkRow",null),f=0;f<e.length;f++){var g=e[f],h=g.className,j=!0;a=="all"?this.currentGradingDisplay=="displayGradeByStepSelectPage"&&h.indexOf("periodAll")==-1&&(j=!1):h.indexOf("period"+a)==-1&&this.currentGradingDisplay!="displayGradeByTeamGradingPage"&&(j=!1);b&&g.getAttribute("isFlagged")!="true"&&
(j=!1);!d&&!(b&&g.getAttribute("isFlagged")=="true")&&h.indexOf("studentWorkRevisionRow")!=-1&&(j=!1);if(c&&(h.indexOf("smartFilterHide")!=-1||h.indexOf("noWork")!=-1))j=!1;j?(g.style.display="",g.id.indexOf("studentWorkRow")!=-1&&(h=this.getStudentWorkIdFromStudentWorkRowId(g.id),g=this.getWorkgroupIdFromStudentWorkRowId(g.id),this.renderStudentWork(h,g))):g.style.display="none"}if(this.gradingHidePersonalInfo&&this.currentGradingDisplay!="displayGradeByStepSelectPage")this.onlyShowWorkOnClick();
this.gradingEnlargeStudentWorkText&&this.enlargeStudentWorkText();if(this.currentGradingDisplayParam!=null&&(e=this.currentGradingDisplayParam[1],e!=null&&this.project.getNodeById(e).getContent().getContentJSON().gradingCriteria!=null))(this.gradingSortByAutoGradedScore=this.isSortByAutoGradedScoreChecked())?this.sortByAutoGradedScore():this.sortByOriginalOrder();this.fixGradingDisplayHeight()};
View.prototype.getStudentWorkIdFromStudentWorkRowId=function(a){var b=a.lastIndexOf("_");return a.substring(b+1)};View.prototype.getWorkgroupIdFromStudentWorkRowId=function(a){var b=a.indexOf("_"),c=a.indexOf("_",b+1);return a.substring(b+1,c)};
View.prototype.enlargeStudentWorkText=function(){var a=document.getElementById("enlargeStudentWorkTextCheckBox");if(a)if(a.checked){this.gradingEnlargeStudentWorkText=!0;for(var a=this.getElementsByClassName(null,"workColumn",null),b=0;b<a.length;b++)a[b].style.cssText="font-size:3.0em"}else{this.gradingEnlargeStudentWorkText=!1;a=this.getElementsByClassName(null,"workColumn",null);for(b=0;b<a.length;b++)a[b].style.cssText=""}this.fixGradingDisplayHeight()};
View.prototype.sortByAutoGradedScore=function(){if(this.project.getNodeById(this.currentGradingDisplayParam[1]).getContent().getContentJSON().gradingCriteria!=null){this.studentWorkRowOrderObjects.sort(this.sortStudentWorkRowsByAutoGradedScore);for(var a=0;a<this.studentWorkRowOrderObjects.length;a++){var b=this.studentWorkRowOrderObjects[a].studentWorkRowId;$("#studentWorkTable").append(document.getElementById(b));if(this.studentWorkRowRevisions[b]!=null)for(var b=this.studentWorkRowRevisions[b],
c=0;c<b.length;c++){var d=b[c];$("#studentWorkTable").append(document.getElementById(d))}}}};View.prototype.sortByOriginalOrder=function(){for(var a=0;a<this.originalStudentWorkRowOrder.length;a++){var b=this.originalStudentWorkRowOrder[a];$("#studentWorkTable").append(document.getElementById(b))}};View.prototype.sortStudentWorkRowsByAutoGradedScore=function(a,b){var c=0;if(a!=null&&b!=null){var d=a.autoGradedScore,e=b.autoGradedScore;d!=null&&e!=null?c=e-d:d==null?c=1:e==null&&(c=-1)}return c};
View.prototype.isWriteAllowed=function(){var a="disabled";this.gradingPermission=="write"?a="":this.gradingPermission=="read"&&(a="disabled");return a};View.prototype.renderAllStudentWorkForNode=function(a){for(var b=this.getVleStatesSortedByUserName(),c=a.id,d=0;d<b.length;d++){var e=b[d],f=e.dataId,e=e.getNodeVisitsWithWorkByNodeId(c),g=null;e.length>0&&(g=e[e.length-1]);this.isSelfRenderingGradingViewNodeType(a.type)&&g!=null&&this.renderStudentWorkFromNodeVisit(g,f)}};
View.prototype.renderAllStudentWorkForWorkgroupId=function(a){for(var b=this.getProject().getNodeIds(),c=this.getVleStateByWorkgroupId(a),d=0;d<b.length;d++){var e=b[d];this.isSelfRenderingGradingViewNodeType(this.getProject().getNodeById(e).type)&&(e=c.getLatestNodeVisitByNodeId(e),e!=null&&this.renderStudentWorkFromNodeVisit(e,a))}};
View.prototype.renderStudentWorkFromNodeVisit=function(a,b){if(a!=null){var c=a.id;a.getLatestWork();var d=a.visitPostTime,e=this.getProject().getNodeById(a.nodeId);$("#studentWorkDiv_"+c).html()==""&&(e.renderGradingView("studentWorkDiv_"+c,a,"",b),$("#studentWorkDiv_"+c).append("<p class='lastAnnotationPostTime'>"+this.getI18NString("timestamp")+": "+new Date(d)+"</p>"))}};
View.prototype.renderStudentWork=function(a,b){var c=this.getStudentWorkByStudentWorkId(a,b);c!=null&&this.renderStudentWorkFromNodeVisit(c,b)};View.prototype.getStudentWorkByStudentWorkId=function(a,b){for(var c=this.getVleStatesSortedByUserName(),d=0;d<c.length;d++){var e=c[d];if(b==null||e.dataId==b)return e.getNodeVisitById(a)}return null};function showDiagram(a,b){var c=document.getElementById(a).innerHTML;document.getElementById(a).innerHTML="";try{new MySystemPrint(c,a,b)}catch(d){}}
function showDiagramNode(){showDiagram($(this).attr("id"),$(this).attr("contentBaseUrl"))}function showDrawNode(){var a=String($(this).html()),a=Utils.decode64(a),a=Utils.text2xml(a);$(this).html("");$(this).append(document.importNode(a.documentElement,!0))}function showSnaps(){var a=String($(this).html()),a=Utils.decode64(a),a=Utils.text2xml(a);$(this).html("");$(this).append(document.importNode(a.documentElement,!0))}
function enlargeDraw(a){window.open("/vlewrapper/vle/node/draw/svg-edit/svg-editor-grading.html").divId=a}function enlargeMS(a){window.open("/vlewrapper/vle/node/mysystem/grading/mysystem.html").divId=a}function refresh(){lock();render(this.contentURL,this.userURL,this.getDataUrl,this.contentBaseUrl,this.getAnnotationsUrl,this.postAnnotationsUrl,this.runId,this.getFlagsUrl,this.postFlagsUrl)}
function removejscssfile(a,b){for(var c=b=="js"?"src":b=="css"?"href":"none",d=document.getElementsByTagName(b=="js"?"script":b=="css"?"link":"none"),e=d.length;e>=0;e--)d[e]&&d[e].getAttribute(c)!=null&&d[e].getAttribute(c).indexOf(a)!=-1&&d[e].parentNode.removeChild(d[e])}typeof eventManager!="undefined"&&eventManager.fire("scriptLoaded","vle/view/grading/gradingview_display.js");View.prototype.openPremadeComments=function(a,b){this.premadeCommentsWindow&&this.premadeCommentsWindow.close();var c=window.open("./premadecomments.html","premadeCommentsWindow","width=800,height=600,scrollbars=1");window.focus&&c.focus();c.eventManager=this.eventManager;c.scriptloader=this.scriptloader;this.premadeCommentsWindow=c;this.commentBoxId=a;this.studentWorkColumnId=b;if(!this.premadeCommentsSubscribed)eventManager.subscribe("scriptsLoaded",this.premadeCommentScriptsLoaded,{id:"premadeCommentWindow",
view:this}),this.premadeCommentsSubscribed=!0;return!1};View.prototype.premadeCommentWindowLoaded=function(){this.premadeCommentsWindow.loadScripts()};View.prototype.premadeCommentScriptsLoaded=function(a,b,c){c.id==b[0]&&c.view.getPremadeComments()};
View.prototype.getPremadeComments=function(){this.premadeCommentLists?this.renderPremadeComments():this.connectionManager.request("GET",1,this.getConfig().getConfigParam("getPremadeCommentsUrl"),{},function(a,b,c){b=c[0];b.premadeCommentLists=$.parseJSON(a);b.renderPremadeComments()},[this],function(){})};
View.prototype.postPremadeComments=function(a,b,c,d,e,f,g,h){this.connectionManager.request("POST",1,this.getConfig().getConfigParam("postPremadeCommentsUrl"),{premadeCommentAction:a,premadeCommentListId:c,premadeCommentListLabel:d,premadeCommentId:e,premadeComment:f,isGlobal:g,premadeCommentListPositions:h},b,[this],function(){})};
View.prototype.renderPremadeComments=function(){var a=this.premadeCommentsWindow.document.getElementById("premadeCommentsListsDiv"),b=$("#"+this.studentWorkColumnId).html(),c="#"+this.commentBoxId.replace(".","\\."),c=$(c).attr("value");$("#premadeCommentsTextArea",this.premadeCommentsWindow.document).attr("value",c);c=b.indexOf('<br><br><br><p class="lastAnnotationPostTime">');b=b.substring(0,c);$("#premadeCommentsStudentWorkDiv",this.premadeCommentsWindow.document).html(b);b=this.getUserAndClassInfo().getUserLoginName();
for(c=0;c<this.premadeCommentLists.length;c++){var d=this.premadeCommentLists[c],e=d.id,f=d.label,g=!1;b==d.owner&&(g=!0);d.premadeComments=this.sortPremadeCommentList(d.premadeComments);f=document.createTextNode(f+" ");a.appendChild(f);g&&(f=createElement(this.premadeCommentsWindow.document,"input",{type:"button",id:"premadeCommentListAddCommentButton_"+e,value:"Add Comment",onclick:'eventManager.fire("addPremadeComment", ['+e+"])"}),a.appendChild(f));f="";g&&(f="myPremadeCommentList");f=createElement(this.premadeCommentsWindow.document,
"ul",{id:"premadeCommentUL_"+e,style:"margin-left: 0px; padding-left: 0px","class":f});a.appendChild(f);for(var h=0;h<d.premadeComments.length;h++){var j=d.premadeComments[h],i=j.id,j=j.comment;this.getPremadeCommentDOMId(i);j=this.createPremadeCommentLI(i,j,e,g);f.appendChild(j);g&&this.makePremadeCommentEditable(i)}}this.makePremadeCommentListsSortable();this.renderPremadeCommentsComplete()};View.prototype.sortPremadeCommentList=function(a){return a=a.sort(this.sortPremadeCommentListByListPositions)};
View.prototype.sortPremadeCommentListByListPositions=function(a,b){return a.listPosition<b.listPosition};View.prototype.makePremadeCommentListsSortable=function(){this.premadeCommentsWindow&&this.premadeCommentsWindow.makeSortable&&this.premadeCommentsWindow.makeSortable(this)};
View.prototype.selectPremadeComment=function(a){var b=$("#premadeCommentsTextArea",this.premadeCommentsWindow.document).attr("value");$("#premadeCommentsTextArea",this.premadeCommentsWindow.document).attr("value",b+$("#"+a,this.premadeCommentsWindow.document).html())};
View.prototype.submitPremadeComment=function(){var a=$("#premadeCommentsTextArea",this.premadeCommentsWindow.document).attr("value"),b="#"+this.commentBoxId.replace(".","\\.");$(b).attr("value",a);$(b).html(a);$(b).focus();$(b).blur();this.premadeCommentsWindow.close()};View.prototype.addPremadeComment=function(a){this.postPremadeComments("addComment",this.addPremadeCommentCallback,a,null,null,null,null)};
View.prototype.addPremadeCommentCallback=function(a,b,c){var b=c[0],a=$.parseJSON(a),c=a.premadeCommentListId,d=a.id,e=b.createPremadeCommentLI(d,a.comment,c,!0);$("#premadeCommentUL_"+c,b.premadeCommentsWindow.document).prepend(e);b.makePremadeCommentEditable(d);b.addPremadeCommentLocally(c,a)};View.prototype.addPremadeCommentLocally=function(a,b){this.getPremadeCommentListLocally(a).premadeComments.push(b)};
View.prototype.createPremadeCommentLI=function(a,b,c,d){var e=this.getPremadeCommentDOMId(a),f=createElement(this.premadeCommentsWindow.document,"li",{id:"premadeCommentLI_"+a,style:"list-style-type:none;margin-left:0px;padding-left:0px"}),g=createElement(this.premadeCommentsWindow.document,"input",{id:"premadeCommentSelectButton_"+a,type:"button",value:"Select",onclick:'eventManager.fire("selectPremadeComment", ["'+e+'"])'}),e=createElement(this.premadeCommentsWindow.document,"p",{id:e,style:"display:inline"});
e.innerHTML=b;f.appendChild(g);f.appendChild(document.createTextNode(" "));f.appendChild(e);if(d)b=createElement(this.premadeCommentsWindow.document,"p",{id:"premadeCommentHandle_"+a,style:"display:inline","class":"premadeCommentHandle"}),b.innerHTML="[Drag Me]",a=createElement(this.premadeCommentsWindow.document,"input",{id:"premadeCommentDeleteButton_"+a,type:"button",value:"Delete",onclick:'eventManager.fire("deletePremadeComment", ['+a+", "+c+"])"}),f.appendChild(document.createTextNode(" ")),
f.appendChild(b),f.appendChild(document.createTextNode(" ")),f.appendChild(a);return f};View.prototype.editPremadeComment=function(a,b,c,d){c=d[0];d=c.editPremadeCommentCallback;a=a.replace("premadeComment_","");c.postPremadeComments("editComment",d,null,null,a,b,null);return b};View.prototype.editPremadeCommentCallback=function(a,b,c){b=c[0];a=$.parseJSON(a);b.editPremadeCommentLocally(a)};
View.prototype.editPremadeCommentLocally=function(a){for(var b=0;b<this.premadeCommentLists.length;b++)for(var c=this.premadeCommentLists[b].premadeComments,d=0;d<c.length;d++){var e=c[d];if(e.id==a.id)e.comment=a.comment}};View.prototype.deletePremadeComment=function(a,b){this.postPremadeComments("deleteComment",this.deletePremadeCommentCallback,b,null,a,null,null)};
View.prototype.deletePremadeCommentCallback=function(a,b,c){b=c[0];a=$.parseJSON(a);$("#premadeCommentLI_"+a.id,b.premadeCommentsWindow.document).remove();b.deletePremadeCommentLocally(a)};View.prototype.deletePremadeCommentLocally=function(a){for(var b=0;b<this.premadeCommentLists.length;b++)for(var c=this.premadeCommentLists[b].premadeComments,d=0;d<c.length;d++)if(c[d].id==a.id){c.splice(d,1);return}};
View.prototype.makePremadeCommentEditable=function(a){a=this.getPremadeCommentDOMId(a);$("#"+a,this.premadeCommentsWindow.document).editInPlace({callback:this.editPremadeComment,params:[this],text_size:60})};View.prototype.getPremadeCommentDOMId=function(a){return"premadeComment_"+a};View.prototype.renderPremadeCommentsComplete=function(){$("#premadeCommentsLoadingP",this.premadeCommentsWindow.document).hide();$("#premadeCommentsTopDiv",this.premadeCommentsWindow.document).show()};
View.prototype.sortUpdate=function(a,b,c){for(var d=[],b=$(a.target).attr("id").replace("premadeCommentUL_",""),a=$(a.target).find("li"),e=0;e<a.length;e++){var f=a[e].id.replace("premadeCommentLI_","");d.push(parseInt(f))}d.reverse();a=c.reOrderPremadeCommentCallback;d=$.stringify(d);c.postPremadeComments("reOrderCommentList",a,b,null,null,null,null,d)};View.prototype.reOrderPremadeCommentCallback=function(a,b,c){b=c[0];a=$.parseJSON(a);b.reOrderPremadeCommentLocally(a.premadeCommentListId,a.listPositions)};
View.prototype.reOrderPremadeCommentLocally=function(a,b){for(var c=this.getPremadeCommentListLocally(a).premadeComments,d=0;d<c.length;d++){var e=c[d],f=b.indexOf(e.id);e.listPosition=f+1}};View.prototype.getPremadeCommentListLocally=function(a){for(var b=0;b<this.premadeCommentLists.length;b++){var c=this.premadeCommentLists[b];if(c.id==a)return c}};typeof eventManager!="undefined"&&eventManager.fire("scriptLoaded","vle/view/grading/gradingview_premadecomments.js");function getStudentWorkgoupIds(){for(var a="",b=0;b<studentWorkgroupIds.length;b++)a!=""&&(a+=":"),a+=studentWorkgroupIds[b];return a}View.prototype.getStudentWorkgroupIdsArray=function(a){for(var b=[],c=0,d=0,e=0;e<this.studentWorkgroupIds.length;e++){var f=this.studentWorkgroupIds[e];b[c]==null?b[c]="":b[c]+=":";b[c]+=f;d++;d==a&&(c+=1,d=0)}return b};
View.prototype.getPeerReviewWork=function(){var a={action:"teacherRequest",runId:this.getConfig().getConfigParam("runId")};this.connectionManager.request("GET",1,this.getConfig().getConfigParam("getPeerReviewUrl"),a,function(a,c,d){d[0].peerReviewWorkArray=$.parseJSON(a)},[this])};
View.prototype.getStudentWork=function(){this.vleStates=[];var a=this.getProject().getNodeIds("HtmlNode:OutsideUrlNode").toString().replace(/,/g,":"),b=this.getStudentWorkgroupIdsArray(10),c=function(a,b,c){b=c[0];c=c[1];a=VLE_STATE.prototype.parseDataJSONString(a,!0);b.vleStates=b.vleStates==null?a:b.vleStates.concat(a);for(a=0;a<b.getStudentDataUrlArray.length;a++)b.getStudentDataUrlArray[a]==c&&b.getStudentDataUrlArray.splice(a,1);b.getStudentDataUrlArray.length==0&&eventManager.fire("getStudentWorkComplete")},
d=function(a,b){var e=b[0],f=b[1];e.connectionManager.request("GET",1,f,null,c,[e,f],d)},e=null,f=!1;if(this.getRevisions)f=this.getRevisions;this.getStudentDataUrlArray=[];for(var g=0;g<b.length;g++)e=b[g],e=this.getConfig().getConfigParam("getStudentDataUrl")+"?userId="+e+"&grading=true&runId="+this.getConfig().getConfigParam("runId")+"&nodeIds="+a+"&getRevisions="+f,this.getStudentDataUrlArray.push(e);for(a=0;a<this.getStudentDataUrlArray.length;a++)e=this.getStudentDataUrlArray[a],this.connectionManager.request("GET",
1,e,null,c,[this,e],d);this.getStudentDataUrlArray.length==0&&eventManager.fire("getStudentWorkComplete")};View.prototype.getVleStateByWorkgroupId=function(a){if(this.vleStates!=null)for(var b=0;b<this.vleStates.length;b++){var c=this.vleStates[b];if(c.dataId==a)return c}return null};
View.prototype.getPeerReviewWorkByReviewerNodeId=function(a,b){if(this.peerReviewWorkArray!=null)for(var c=0;c<this.peerReviewWorkArray.length;c++){var d=this.peerReviewWorkArray[c];if(d.reviewerWorkgroupId==a&&d.nodeId==b)return d}return null};View.prototype.getPeerReviewWorkByWorkerNodeId=function(a,b){if(this.peerReviewWorkArray!=null)for(var c=0;c<this.peerReviewWorkArray.length;c++){var d=this.peerReviewWorkArray[c];if(d.workgroupId==a&&d.nodeId==b)return d}return null};
View.prototype.getIdeaBaskets=function(){this.connectionManager.request("GET",1,this.getConfig().getConfigParam("getIdeaBasketUrl"),{action:"getAllIdeaBaskets"},function(a,b,c){for(var b=c[0],a=$.parseJSON(a),c=[],d=0;d<a.length;d++){var e=new IdeaBasket(a[d]);c.push(e)}b.ideaBaskets=c;eventManager.fire("getIdeaBasketsComplete")},[this])};typeof eventManager!="undefined"&&eventManager.fire("scriptLoaded","vle/view/grading/gradingview_studentwork.js");
if(typeof eventManager != 'undefined'){eventManager.fire('scriptLoaded', 'vle/minified/grading_min.js');}
