AssessmentListNode.prototype=new Node;AssessmentListNode.prototype.constructor=AssessmentListNode;AssessmentListNode.prototype.parent=Node.prototype;AssessmentListNode.authoringToolName="Questionnaire";AssessmentListNode.authoringToolDescription="Students answer a collection of questions that require text or multiple choice answers";function AssessmentListNode(a,b){this.view=b;this.type=a}AssessmentListNode.prototype.parseDataJSONObj=function(a){return ASSESSMENTLISTSTATE.prototype.parseDataJSONObj(a)};
AssessmentListNode.prototype.render=function(a,b,c){this.content.getContentJSON().isMustCompleteAllPartsBeforeExit&&this.view.eventManager.fire("addConstraint",{type:"WorkOnXConstraint",x:{id:this.id,mode:"node"},id:this.utils.generateKey(20)});Node.prototype.render.call(this,a,b,c)};
AssessmentListNode.prototype.isCompleted=function(){var a=this.view.state.getNodeVisitsByNodeId(this.id);if(a!=null)for(var b=0;b<a.length;b++){var c=a[b];if(c.nodeStates!=null)for(var d=0;d<c.nodeStates.length;d++){var e=c.nodeStates[d];if(e.isSubmit||e.submit)return!0}}return!1};
AssessmentListNode.prototype.getPrompt=function(){var a=this.content.getContentJSON(),b=null;a.prompt!=null&&(b=a.prompt+"<br/>");for(var c=0;c<a.assessments.length;c++){var d=a.assessments[c];b+="Part "+(c+1)+": "+d.prompt;if(d.type=="radio"){b+="<br/>&nbsp;&nbsp;&nbsp;&nbsp;Choices:<br/>";for(var e=0;e<d.choices.length;e++)b+="&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+d.choices[e].text,e!=d.choices.length-1&&(b+="<br/>")}b+="<br/>"}return b};AssessmentListNode.prototype.onExit=function(){if(this.contentPanel)try{if(this.contentPanel.onExit)try{this.contentPanel.onExit()}catch(a){}}catch(b){history.back()}};
AssessmentListNode.prototype.getHTMLContentTemplate=function(){return createContent("node/assessmentlist/assessmentlist.html")};NodeFactory.addNode("AssessmentListNode",AssessmentListNode);typeof eventManager!="undefined"&&eventManager.fire("scriptLoaded","vle/node/assessmentlist/AssessmentListNode.js");View.prototype.assessmentlistDispatcher=function(a,b,c){a=="assessmentlistPromptChanged"?c.AssessmentListNode.updatePrompt():a=="assessmentlistFieldUpdated"?c.AssessmentListNode.fieldUpdated(b[0],b[1]):a=="assessmentlistRadioItemFieldUpdated"?c.AssessmentListNode.radioItemFieldUpdated(b[0],b[1],b[2]):a=="assessmentlistAddChoice"?c.AssessmentListNode.addChoice(b[0]):a=="assessmentlistRadioItemRemoveChoice"?c.AssessmentListNode.radioItemRemoveChoice(b[0],b[1]):a=="assessmentlistAddNewItem"?c.AssessmentListNode.addNewItem(b[0]):
a=="assessmentlistRemoveItem"?c.AssessmentListNode.removeItem(b[0]):a=="assessmentlistStarterSentenceUpdated"?c.AssessmentListNode.starterSentenceChanged(b[0]):a=="assessmentlistStarterOptionChanged"?c.AssessmentListNode.starterOptionChanged(b[0]):a=="assessmentlistUpdateRichText"?c.AssessmentListNode.updateRichText(b[0]):a=="assessmentOptionChanged"?c.AssessmentListNode.optionChanged(b[0]):a=="assessmentListUpdateImportantReviewSequencePart"?c.AssessmentListNode.updateImportantReviewSequencePart(b[0]):
a=="assessmentListPeerReviewPercentageTriggerUpdated"?c.AssessmentListNode.peerReviewPercentageTriggerUpdated():a=="assessmentListPeerReviewNumberTriggerUpdated"?c.AssessmentListNode.peerReviewNumberTriggerUpdated():a=="assessmentListPeerReviewAuthoredWorkUpdated"?c.AssessmentListNode.peerReviewAuthoredWorkUpdated():a=="assessmentListPeerReviewStepNotOpenCustomMessageUpdated"&&c.AssessmentListNode.peerReviewStepNotOpenCustomMessageUpdated()};
for(var events=["assessmentlistPromptChanged","assessmentlistFieldUpdated","assessmentlistRadioItemFieldUpdated","assessmentlistAddNewItem","assessmentlistRemoveItem","assessmentlistAddChoice","assessmentlistRadioItemRemoveChoice","assessmentlistUpdateRichText","assessmentlistStarterOptionChanged","assessmentlistStarterSentenceUpdated","assessmentOptionChanged","assessmentListUpdateImportantReviewSequencePart","assessmentListPeerReviewPercentageTriggerUpdated","assessmentListPeerReviewNumberTriggerUpdated",
"assessmentListPeerReviewAuthoredWorkUpdated","assessmentListPeerReviewStepNotOpenCustomMessageUpdated"],x=0;x<events.length;x++)componentloader.addEvent(events[x],"assessmentlistDispatcher");typeof eventManager!="undefined"&&eventManager.fire("scriptLoaded","vle/node/assessmentlist/assessmentListEvents.js");
if(typeof eventManager != 'undefined'){eventManager.fire('scriptLoaded', 'vle/node/assessmentlist/assessmentlist_core_min.js');}
